function [fitresult, gof] = createFitL(xi, rest)
%CREATEFIT(XI,REST)
% (c)Maria Pires Pacheco 2016
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xi
%      Y Output: rest
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Feb-2016 19:40:04


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xi, rest );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.StartPoint = [0.0442312785349232 -0.515420615759673 2.77989514663167];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
end


