% The COBRAToolbox: This script tests the functionality of 
%                   calculateFluxShifts.m function
%
% Purpose:
%     - For testing the IgemRNA post-optimization task called "Calculate flux
%     shifts between phenotypes" which calculates flux differences for each
%     reaction from two (or more if target = "All") result model files generated by createContextSpecificModel.m. 
%
% Authors:
%     - Kristina Grausa 05/16/2022 - created 
%     - Kristina Grausa 08/22/2022 - standard header and formatting
%     - Farid Zare      02/12/2024 - Repository address corrected
%

global CBTDIR

% define the required solvers
requiredSolvers = {'needsLP', 'matlab'};

% check if the specified requirements are fullfilled
solvers = prepareTest('needsLP',true);

% save the current path and initialize the test
currentDir = cd(fileparts(which(mfilename)));

% determine the test path for references
testPath = pwd;

% set the tolerance
tol = 1e-8;

% set function params
source = {'SRR8994357_WT';};
target = {'SRR8994378_S47D';};

% Load Reference Data
load('refData_flux_shifts.mat');

for k = 1:length(solvers.LP)
    solverLPOK = changeCobraSolver(solvers.LP{k}, 'LP', 0);

    if solverLPOK
       calculateFluxShifts(source, target);
       
       fprintf(' -- Running testFluxShifts.m using the solver interface: %s ... ', solvers.LP{k});

       % load the result
       resultPath = ['resultsPostOptimization', filesep, 'fluxShifts', filesep, 'SRR8994378_S47D_flux_shifts.xls'];
       resultData = readtable(resultPath);
       
       % Compare the result with reference data
       assert(isequaln(refData, resultData));
       
       % output a success message
       fprintf('Done.\n');
    end
end

% change the directory
cd(currentDir);
