function [modelOut,removeMetBool,removeRxnBool] = manuallyAdaptRecon3(model,printLevel)
% manually adapts the reactions in recon 3
%
%INPUT
% model             a recon3 draft
% printLevel
%
%OUTPUT
% modelOut          manually adapted Recon3
% removeMetBool     removed metabolites
% removeRxnBool     removed reactions

if ~exist('printLevel','var')
    printLevel=1;
end

[nMet,nRxn]=size(model.S);

fprintf('%6s\t%6s\n','#mets','#rxns')
fprintf('%6u\t%6u\t%s\n',nMet,nRxn,' totals before manuallyAdaptRecon3.')

%replace Ex_ to make them consistently EX_
for n=1:nRxn
    rxnAbbr=model.rxns{n};
    if length(rxnAbbr)>=3
        if strcmp('Ex_',rxnAbbr(1:3))
            rxnAbbr(1:3)='EX_';
            model.rxns{n}=rxnAbbr;
        end
    end
end

% metabolites with missing formulae
% ncaproic[e]
% xol24oh24g[c]
% xol24oh24g3s[c]
% protein[c]
% h[i]

%Rename some of the biomass reactions to make them more obviously exchange
%reactions
model.rxns{strcmp(model.rxns,'biomass_reaction')}= 'EX_biomass_reaction';
model.rxns{strcmp(model.rxns,'biomass_maintenance')}= 'EX_biomass_maintenance';
model.rxns{strcmp(model.rxns,'biomass_maintenance_noTrTr')}= 'EX_biomass_maintenance_noTrTr';

%ATP hydrolysis is not imbalanced like all the other demand reactions so
%give it a different accronym ATPM = ATP Maintenance
bool=strcmp('DM_atp_c_',model.rxns);
model.rxns{bool}='ATPM';
    
%remove every reaction involving at least one of the following metabolites
removeMetAbbr={...
'HC02111[c]',... %Adenosine-5'-Triphosphate-Energy
'HC02111[m]',...
'HC02112[r]',...%Nadh-Redox-Potential
'HC02112[c]',... 
'HC02112[m]',...
'HC02112[x]',...
'HC02113[r]',...%Virtual ReactionPotential Definition
'HC02113[c]',...
'HC02113[m]',...
'HC02113[x]',...
'HC02114[c]',...%Fadh-Redox-Potential
'HC02115[m]',...%Proton-Gradient
'HC02115[c]',...
'Temp001[c]',...%Biomass
'HC01797[c]'};  %Activated Methyl Group (another 'potential' molecule)


removeMetBool=false(nMet,1);
for i=1:length(removeMetAbbr)
    bool=strcmp(removeMetAbbr{i},model.mets);
    if any(bool)
        removeMetBool(bool)=1;
    else
        fprintf('%s\t%s\n',removeMetAbbr{i},' molecule to be removed but not found.')
    end
end

%remove any reaction involving at least one removeMets{i}
removeRxnBoolFromMet = getCorrespondingCols(model.S,removeMetBool,true(nRxn,1),'inclusive');

if 1
%remove each of the following reactions, and any metabolite exclusively
%involved in these reactions
removeRxnAbbr={...
'HMR_7745',...	%M01388[c] 	<=>	glc_D[c] 
'TAG_HSad',...	%2 h2o[c] + pmtcoa[c] + 2 lnlccoa[c] + stcoa[c] + 2 odecoa[c] + 2 glyc3p[c] 	->	2 pi[c] + 6 coa[c] + 2 tag_hs[c] 
'TAG_HSad_NE',...	%2 h2o[c] + pmtcoa[c] + hdcoa[c] + tdcoa[c] + stcoa[c] + 2 odecoa[c] + 2 glyc3p[c] 	->	2 pi[c] + 6 coa[c] + 2 tag_hs[c] 
'TAG_HSad_E',...	%2 h2o[c] + arachdcoa[c] + lnlncacoa[c] + tmndnccoa[c] + 2 lnlccoa[c] + c226coa[c] + 2 glyc3p[c] 	->	2 pi[c] + 6 coa[c] + 2 tag_hs[c] 
'RTOTAL3FATPc',...	%atp[c] + coa[c] + Rtotal3[e] 	->	amp[c] + ppi[c] + Rtotal3coa[c] 
'RTOT_2',...	%R2coa_hs[c] + R4coa_hs[c] 	->	2 Rtotal2coa[c] 
'RTOT_3',...	%R1coa_hs[c] + R2coa_hs[c] 	->	2 Rtotal3coa[c] 
'RTOT2',...	    %R2coa_hs[c] 	->	Rtotalcoa[c] 
'RTOT3',...	    %R3coa_hs[c] 	->	Rtotalcoa[c] 
'RTOT4',...	    %R4coa_hs[c] 	->	Rtotalcoa[c] 
'RTOT5',...	    %R5coa_hs[c] 	->	Rtotalcoa[c] 
'LPSe',...	    %h2o[e] + tag_hs[e] 	->	h[e] + dag_hs[e] + Rtotal3[e] 
'RTOTAL3t',...	%Rtotal3[e] 	<=>	Rtotal3[c]
'ARTFR13',...	%tdcoa[c] 	->	0.875 R1coa_hs[c] 
'ARTFR202',...	%h[m] + nadph[m] + 2 fadh2[m] + lnlncacoa[c] 	->	nadp[m] + 2 fad[m] + 1.125 R2coa_hs[c] 
'ARTFR203',...	%h[m] + nadph[m] + 2 fadh2[m] + lnlncgcoa[c] 	->	nadp[m] + 2 fad[m] + 1.125 R2coa_hs[c] 
'ARTFR204',...	%2 h[m] + 2 nadph[m] + 2 fadh2[m] + strdnccoa[c] 	->	2 nadp[m] + 2 fad[m] + 1.125 R2coa_hs[c] 
'ARTFR205',...	%h[m] + nadph[m] + 2 fadh2[m] + dlnlcgcoa[c] 	->	nadp[m] + 2 fad[m] + 1.25 R2coa_hs[c] 
'ARTFR206',...	%2 h[m] + 2 nadph[m] + 2 fadh2[m] + arachdcoa[c] 	->	2 nadp[m] + 2 fad[m] + 1.25 R2coa_hs[c] 
'ARTFR207',...	%arachcoa[c] 	->	1.25 R2coa_hs[c] 
'ARTFR209',...	%2 h[m] + 2 nadph[m] + 2 fadh2[m] + adrncoa[c] 	->	2 nadp[m] + 2 fad[m] + 1.375 R2coa_hs[c] 
'ARTFR210',...	%h[m] + nadph[m] + fadh2[m] + lnlccoa[c] 	->	nadp[m] + fad[m] + 1.125 R2coa_hs[c] 
'ARTFR211',...	%2 h[m] + 2 nadph[m] + 3 fadh2[m] + clpndcoa[c] 	->	2 nadp[m] + 3 fad[m] + 1.375 R2coa_hs[c] 
'ARTFR212',...	%2 h[m] + 2 nadph[m] + 3 fadh2[m] + dcsptn1coa[c] 	->	2 nadp[m] + 3 fad[m] + 1.375 R2coa_hs[c] 
'ARTFR213',...	%3 h[m] + 3 nadph[m] + 3 fadh2[m] + c226coa[c] 	->	3 nadp[m] + 3 fad[m] + 1.375 R2coa_hs[c] 
'ARTFR41',...	%fadh2[m] + hdcoa[c] 	->	fad[m] + R4coa_hs[c] 
'ARTFR45',...	%fadh2[m] + nrvnccoa[c] 	->	fad[m] + 1.5 R4coa_hs[c] 
'ARTFR52',...	%hexccoa[c] 	->	1.625 R5coa_hs[c] 
'ARTFR53',...	%2 h[m] + 2 nadph[m] + 2 fadh2[m] + eicostetcoa[c] 	->	2 nadp[m] + 2 fad[m] + 1.25 R5coa_hs[c] 
'VLDL_HSDEG',...%(Grossly imbalancd, 158 H, 104 C, 58 O, 2 P, 2 N, 29 R) 5 h2o[e] + vldl_hs[e] 	->	2 chsterol[e] + 2 pchol_hs[e] + 5 Rtotal[e] + 5 Rtotal2[e] + 5 Rtotal3[e] + 5 glyc[e] + 0.2 HC00005[e] + 0.2 HC00006[e] + 0.2 HC00007[e] + 0.2 HC00008[e] 
'HMR_9577',... %Non-Specific Serine/Threonine Protein Kinase: atp[c] + M00196[c] -> adp[c] + M02742[c] (M02742 is a "Phosphoprotein")
'HMR_9578',... %Phosphoprotein Phosphohydrolase: h2o[c] + M02742[c] -> pi[c] + M00196[c] (M02742 is a "Phosphoprotein")
'r1092',...%Albumin Protein Assembly
'r1093',...%Serpin Peptidase Inhibitor, Clade A (Alpha-1 Antiproteinase, Antitrypsin), Member 3 Protein Assembly
'r1094',...%Serpin Peptidase Inhibitor, Clade A (Alpha-1 Antiproteinase, Antitrypsin), Member 1 Protein Assembly
'r1095',...%Apolipoprotein B Protein Assembly
'r1096',...%NADH Dehydrogenase (Ubiquinone) 1, AlphaBeta Subcomplex, 1 Protein Assembly
'r1097',...%Acp Protein Assembly
'r1098',...%Apo-Cib Protein Assembly
'r1099',...%Apo-Cii Protein Assembly
'r1100',...%Apo-Ciii Protein Assembly
'r1101',...%Fibrinogen Alpha Chain Protein Assembly
'r1102',...%Haptoglobin Protein Assembly
'r1103',...%Plasminogen Protein Assembly
'r1104',...%Prothrombin Protein Assembly
'r1105',...%T9 Protein Assembly
'r1112',...%Apo-E Protein Assembly
'r1113',...%Apo-Ai Protein Assembly
'r1293',...%Adf Protein Assembly
'r1294',...Mtrx Protein Assembly
'r1402',...%Glycogenin Protein Assembly
'r1333',...%Protein Degradation
'r1334',...%Protein Degradation
'r1335',...%Protein Degradation
'r1336',...%Protein Degradation
'r1337',...%Protein Degradation
'r1338',...%Protein Degradation
'r1339',...%Protein Degradation
'r1340',...%Protein Degradation
'r1341',...%Protein Degradation
'r1342',...%Protein Degradation
'r1343',...%Protein Degradation
'r1344',...%Protein Degradation
'r1345',...%Protein Degradation
'r1346',...%Protein Degradation
'r1347',...%Protein Degradation
'r1348',...%Protein Degradation
'r1349',...%Protein Degradation
'r1350',...%Protein Degradation
'r1351',...%Protein Degradation
'r1352',...%Protein Degradation
'r1353',...%Protein Degradation
'r1354',...%Protein Degradation
'r1355',...%Protein Degradation
'r1356',...%Protein Degradation
'r1357',...%Protein Degradation
'r1358',...%Protein Degradation
'r1359',...%Protein Degradation
'r1403',...%Protein Degradation
'r1096',...%NADH Dehydrogenase (Ubiquinone) 1, AlphaBeta Subcomplex, 1 Protein Assembly 
'HMR_3537',...%60 metabolites involved in the formation of a 'cholesterol ester pool'   
'HMR_3622',...%60 metabolites involved in the formation of a 'cholesterol ester pool'    
'arachidonates',...%exchange reaction from Edinburgh
'HMR_9725',...
'HMR_biomass_Renalcancer',...
'biomass_components',...
'cofactors_vitamins',...
'vitaminA',...
'vitaminD',...
'vitaminE',...
'xenobiotics',...
'arachidonates',...
'steroids',...
'others',... %HMR "Artificial reactions" 
'HMR_0001',...%	Lipoprotein Lipase (Crazy stoichiometry:  M01570[e] -> 77243.0 M02956[e] + M01569[e])
'HMR_0006',...%	Lipoprotein Lipase (ditto: M03147[e] -> 10385.0 tag_hs[e] + M03146[e])
'HMR_0007',... %crazy stoichiometry
'HMR_0010',...
'HMR_0011',...
'HMR_0012',...
'HMR_0013',...
'HMR_0014',...
'HMR_0015',...%added on March 23rd
'HMR_0016',...%added on March 23rd
'HMR_0477',...
'HMR_0545',...
'HMR_0546',...
'HMR_0547',...
'HMR_0548',...
'HMR_0549',...
'HMR_0550',...
'HMR_0551',...
'HMR_0552',...
'HMR_0553',...
'HMR_0555',...
'HMR_0556',...
'HMR_0557',...
'HMR_0558',...
'HMR_0559',...
'HMR_0560',...
'HMR_0561',...
'HMR_0685',...
'HMR_0686',...
'HMR_0687',...
'HMR_0688',...
'HMR_0689',...
'HMR_0690',...
'HMR_0691',...
'HMR_0692',...
'HMR_1185',...
'HMR_1227',...
'HMR_5233',...
'HMR_5234',...
'HMR_5238',...
'HMR_5239',...
'HMR_5243',...
'HMR_5244',...
'HMR_5247',...
'HMR_5257',...
'HMR_9022',...
'HMR_0031',...
'HMR_0032',...%'HMR "Pool reactions"
'HMR_5151',...
'HMR_5152',...
'HMR_5153',...
'HMR_5154',...
'HMR_5155',...
'HMR_5156',...
'HMR_5157',...
'HMR_5158',...
'HMR_5159',...
'HMR_5160',...
'HMR_5161',...
'HMR_5162',...
'HMR_5163',...
'HMR_5164',...
'HMR_5165',...
'HMR_5166',...
'HMR_5167',...
'HMR_5168',...
'HMR_5169',...
'HMR_5170',...
'HMR_5171',...
'HMR_5172',...
'HMR_5173',...
'HMR_5174',...%'HMR/Hepatonet "Protein assembly"
'HMR_5258',...
'HMR_5259',...
'HMR_5260',...
'HMR_5261',...
'HMR_5262',...
'HMR_5263',...
'HMR_5264',...
'HMR_5265',...
'HMR_5266',...
'HMR_5267',...
'HMR_5268',...
'HMR_5269',...
'HMR_5270',...
'HMR_5271',...
'HMR_5272',...
'HMR_5273',...
'HMR_5274',...
'HMR_5275',...
'HMR_5276',...
'HMR_5277',...
'HMR_5278',...
'HMR_5279',...
'HMR_5280',...
'HMR_5281',...
'HMR_5282',...
'HMR_5283',...
'HMR_5284',...
'HMR_5285',...
'HMR_5286',...
'HMR_5287',...
'HMR_5288',...
'HMR_5289',...
'HMR_5290',...
'HMR_5291',...
'HMR_9817',...
'HMR_9818',...%'HMR/Hepatonet "Protein degradation"
'HMR_7282',...
'HMR_7616',...
'HMR_7617',...
'HMR_7618',...
'HMR_7619',...
'HMR_9735',...
'HMR_7621',...
'HMR_7622',...
'HMR_7624',...
'HMR_9488',... % ATP:Phosphorylase-B Phosphotransferase;	Miscellaneous
'HMR_9494',... % [Myosin-Light-Chain]-Phosphate Phosphohydrolase	Miscellaneous
'HMR_9516',... %h2o[c] + M00220[c] -> M00219[c] + pi[c] Miscellaneous
'HMR_7037',... %HMR_7037	Xenobiotics metabolism
'HMR_7047',...%HMR_7047	Xenobiotics metabolism
'HMR_7626',...% 'HMR/Hepatvonet "Protein modification" % The ones below are still to be confirmed by Ines ...
'HMR_4770',...% duplicate of RE3052C with incorrect protons
'HMR_4769',...% duplicate of RE3637C with incorrect protons
'RE3469C',... % incorrect version of RE3526C	o2[c] + 2 CE2084[c] 	->	2 CE7097[c], ormula for http://vmh.uni.lu/#metabolite/CE7097 is wrong?
'r1386',...	  % Virtual ReactionPotential Definition - thermodynamics should not be done as a hack
'HMR_7160',...%	Dna-Directed DNA Polymerase - macromolecular synthesis reactions should not be in as a hack
'HMR_7163',...%	Exodeoxyribonuclease Iii - macromolecular synthesis reactions should not be in as a hack
'HMR_7164',...%	Exodeoxyribonuclease Iii - macromolecular synthesis reactions should not be in as a hack
'HMR_2030',...% HMR_2030	o2[c] + h[c] + whtststerone[c] 	->	h2o[c] + M00434[c] 
'HMR_2033',...% o2[c] + h[c] + M00431[c] 	->	h2o[c] + M00433[c] 
'NM_3',...    % NM_3	CE5025[c] 	->	neuromelanin[c] - this needs to be revised
'RE2031M',...%RE2031M, RE2031, accoa[m] + ala_L[m] <=> h[m] + coa[m] + CE1554[m], Alanine and aspartate metabolism --- CE1554 prime suspect for mispecification only involved in 2 reactions
'RE2642C',...%RE2642C, RE2642, h2o[c] + CE1554[c] <=> ac[c] + ala_L[c], Alanine and aspartate metabolism
'HMR_7599',...%start of Ines temp list,
'ARTFR11',... % R Group Artificial Flux	R group synthesis
'ARTFR12',... % R Group Artificial Flux (C16:1)	R group synthesis
'ARTFR61',... % R Group Artificial Flux	R group synthesis
'ARTPLM1',... % R Group to Palmitate Conversion	R group synthesis
'ARTPLM1m',...% R Group to Palmitate Conversion	R group synthesis
'ARTPLM2',... % R Group to Palmitate Conversion	R group synthesis
'ARTPLM2m',...% R Group to Palmitate Conversion	R group synthesis
'HMR_4763',... %Heme Oxygenase (Biliverdin-Producing) fadh2[c] + M02050[c] + 3.0 o2[c] -> biliverd[c] + co[c] + fad[c] + fe3[c] + 3.0 h2o[c] + M01957[c] Miscellaneous - Haemoglobin
'HMR_7901',... %M02050[c] <=> M02050[e] Miscellaneous - Haemoglobin
'HMR_9717',... %M01957[c] + pheme[c] -> M02050[c] Miscellaneous - Haemoglobin
'EX_M02050(e)',... %M02561[e] <=> - Haemoglobin
'EX_M02723(e)',... %M02050[e] <=> - Haemoglobin
'',... 	% THESE REACTIONS BELOW ARE NECESSARY TO ELIMINATE FROM THE MODEL TO MAKE IT CONSISTENT
'r0368',...  CoA:Apo-[Acyl-Carrier-Protein] Pantetheinephosphotransferase	CoA synthesis
'r1316',...	Fatty Acid Synthase Polyunsaturated Fatty Acid Biosynthesis	Fatty acid synthesis
'r1479',...	          Long-Chain-Acyl Coenzyme A Dehydrogenase	Miscellaneous
'RE3268C',...	Phosphatidylinositol-3,4,5-Trisphosphate 3-Phosphatase	Phosphatidylinositol phosphate metabolism
'LCAT26e',...	Lecithin-Cholesterol Acyltransferase, Formation of Cholesterol-Ester (20:5)	Cholesterol metabolism
'LCAT28e',...	Lecithin-Cholesterol Acyltransferase, Formation of Cholesterol-Ester (22:6)	Cholesterol metabolism
'AGPAT2',...	1-Acylglycerol-3-Phosphate O-Acyltransferase 1 (C16:0)	Glycerophospholipid metabolism
'AGPAT3',...	1-Acylglycerol-3-Phosphate O-Acyltransferase 1 (C18:1)	Glycerophospholipid metabolism
'VACCtl',...	          Intracellular Transport of Vaccenic Acid	Transport, lysosomal
'HMR_0884',...	Glycoprotein-Fucosylgalactoside Alpha-N-Acetylgalactosaminyltransferase	Glycosphingolipid metabolism
'HMR_2253',...	           Oleoyl-[Acyl-Carrier-Protein] Hydrolase	Fatty acid synthesis
'HMR_4768',...	                                          HMR_4768	Heme synthesis
'HMR_7656',...	ATP:1D-Myo-Inositol-5-Diphosphate-Pentakisphosphate Phosphotransferase	Inositol phosphate metabolism
'HMR_0898',...	                                          HMR_0898	Glycosphingolipid metabolism
'HMR_2605',...	                  Carnitine O-Palmitoyltransferase	Fatty acid oxidation
'HMR_9733',...	                                          HMR_9733	Tyrosine metabolism
'HMR_0790',...	                         Sulfatide Sulfohydrolase;	Glycosphingolipid metabolism
'DOLGPP_Uer',...	Dolichyl-Beta-D-Glucosyl-Phosphate Dolichylphosphohydrolase (Uterus)	N-glycan synthesis
'DOLMANP_Lter',...	       Dolichol-Phosphate Mannose Flippase (Liver)	N-glycan synthesis
'DOLP_Lter',...	               Dolichol Phosphate Flippase (Liver)	N-glycan synthesis
'DOLPMT3_Ler',...	Dolichyl-Phosphate-Mannose-Glycolipid Alpha-Mannosyltransferase (Liver)	N-glycan synthesis
'G12MT2_L',...	Glycolipid 1, 2-Alpha-D-Mannosyltransferase (Liver)	N-glycan synthesis
'GLCNACT_L',...	UDP-GlcNac:N-Acetyl-D-Glucosaminyl Diphosphodolichol N-Acetyl-D-Glucosaminyltransferase (Liver)	N-glycan synthesis
'UDPDOLPT_U',...UDPglucose:Dolichyl-Phosphate Beta-D-Glucosyltransferase (Uterus)	N-glycan synthesis
'RE1827C',...	                                           RE1827C	Bile acid synthesis
'RE3514C',...	                   Leukotriene-B4 20-Monooxygenase	Arachidonic acid metabolism
'XOLEST204tl',...	Intracellular Transport of Cholesteryl Arachidonate, Cholesterol-Ester (20:4, Delta 5, 8, 11, 14)	Transport, lysosomal
 'MCOATA',...	               Malonyl Coenzyme A-Acp Transacylase	Fatty acid oxidation% 'FUT31g',...	Fucosyltransferase 3 (Galactoside 3 (4)-L-Fucosyltransferase, Lewis Blood Group Included) 1	Blood group synthesis
'FUT31g',...	Fucosyltransferase 3 (Galactoside 3 (4)-L-Fucosyltransferase, Lewis Blood Group Included) 1	Blood group synthesis
'NM_1',...	%CE1562[c] 	->	neuromelanin[c] 
'NM_5',...	%CE5026[c] 	->	neuromelanin[c] 
'NM_6',...	%CE1261[c] 	->	neuromelanin[c] 
'NM_7',...	%4glu56dihdind[c] 	->	neuromelanin[c] 
'NM_2',...	%ind56qn[c] 	->	neuromelanin[c] 
'NM_8',...	%CE4888[c] 	->	neuromelanin[c] 
'PROTEIN_BS',...%Macromolecular synthesis should not be part of Recon3, Added March 23rd
''};

%'CYOOm3',...% to be replaced by two other mass balanced reactions - Ines
% 'MAN6PI',...	                     Mannose-6-Phosphate Isomerase	Fructose and mannose metabolism
% 'OHCLtm',... %Temp
% 'PROTEIN_BS',... %Temp
% 'DM_PROTEIN',... %Temp
%'RE2704C',...%RE2704C	yvite[c] 	->	h[c] + no2[c] + CE7047[c] %no nitrogen involved, mispecified reaction

    removeRxnBool=false(nRxn,1);
    for i=1:length(removeRxnAbbr)
        bool=strcmp(removeRxnAbbr{i},model.rxns);
        if any(bool)
            removeRxnBool(bool)=1;
        else
            if printLevel>2
                fprintf('%s\t%s\n',removeRxnAbbr{i},' reaction to be removed but not found.')
            end
        end
    end
    removeRxnBool=removeRxnBool | removeRxnBoolFromMet;
else
    %also remove all HMR reactions
    removeRxnAbbr={...
        ''... %After removing the HMR_ reactions, removing all of these below will give a
        ''... %fully stoichiometrically consistent model
        'r1316',...	%TEMP   %h[c] + nadph[c] + HC02099[c]  -> nadp[c] + HC01988[c]
        'r0368',...	 %TEMP  %coa[c] + HC01161[c] 	->	pap[c] + ACP[c]
        'RE3268C',...%TEMP	%h2o[c] + pail345p_hs[c] 	->	pi[c] + mi34p[c]
        'LCAT26e',...%TEMP	%chsterol[e] + pchol_hs[e] 	->	lpchol_hs[e] + xolest205_hs[e]
        'LCAT28e',...%TEMP	%chsterol[e] + pchol_hs[e] 	->	lpchol_hs[e] + xolest226_hs[e]
        'AGPAT2',... %TEMP	%alpa_hs[c] + pmtcoa[c] 	->	coa[c] + pa_hs[c]
        'AGPAT3',... %TEMP	%alpa_hs[c] + odecoa[c] 	->	coa[c] + pa_hs[c]
        'AGPAT4',... %TEMP	%alpa_hs[c] + lnlccoa[c] 	->	coa[c] + pa_hs[c]
        'LCAT27e',...%TEMP	%chsterol[e] + pchol_hs[e]  -> lpchol_hs[e] + xolest204_hs[e]
        '34HPPOR',...%NOT ATOM MAPPED YET SUPPOSED TO BE BALANCED
        'LTDCL',... %NOT ATOM MAPPED YET SUPPOSED TO BE BALANCED
        'PEAMNO',...%NOT ATOM MAPPED YET SUPPOSED TO BE BALANCED
        'C03990tx',...%NOT ATOM MAPPED YET SUPPOSED TO BE BALANCED
        'VACCtl',...%NOT ATOM MAPPED YET SUPPOSED TO BE BALANCED
        'HC02191c',...%ONLY ATOM MAPPED BY RDT;-4 H, -3 C;h2o[c] + nadp[c] + CE1298[c]  -> 2 h[c] + nadph[c] + HC02191[c]
        '5AOPtm',...	%ATOM MAPPED         5-Aminolevulinate Mitochondrial Transport	Heme synthesis
        'C3STKR2r',...	%ATOM MAPPED            C-3 Sterol Keto Reductase (Zymosterol)	Cholesterol metabolism
        'DCIm',...	    %ATOM MAPPED         Dodecenoyl-Coenzyme A Delta Isomerase	Fatty acid oxidation
        'DPMVDx',...	%ATOM MAPPED                 Diphosphomevalonate Decarboxylase	Cholesterol metabolism
        'LNS14DM',...	%ATOM MAPPED Cytochrome P450 Lanosterol 14-Alpha-Demethylase (NADP)	Cholesterol metabolism
        'r1253',...	   %ATOM MAPPED             Long-Chain-Fatty-Acid---Coa Ligase	Fatty acid oxidation
        'PMEVKc'...	%ATOM MAPPED                 Phosphomevalonate Kinase, Cytosol	Squalene and cholesterol synthesis
        ''};

    removeRxnBool=false(nRxn,1);
    for i=1:length(removeRxnAbbr)
        bool=strcmp(removeRxnAbbr{i},model.rxns);
        if any(bool)
            removeRxnBool(bool)=1;
        else
            if printLevel
                fprintf('%s\t%s\n',removeRxnAbbr{i},' reaction to be removed but not found.')
            end
        end
    end
    
    HMRRxnBool=strncmp('HMR_', model.rxns, 6)==1;
    %also remove all HMR reactions
    removeRxnBool=removeRxnBool | removeRxnBoolFromMet | HMRRxnBool;
end
        
removeRxnList=model.rxns(removeRxnBool);

removeMetBool = getCorrespondingRows(model.S,true(nMet,1),removeRxnBool,'exclusive');
%removeMetList=model.mets(removeMetBool);

modelOut = removeRxns(model,removeRxnList);
end

%Mass and charge balanced
%'HMR_7099',...% h[c] + M00242[c] + nadph[c] + o2[c] -> h2o[c] + M00636[c] + M02143[c] + nadp[c] 

% 'HMR_8271',...
% 'HMR_8287',...
% 'HMR_6397',...
% 'HMR_0979',...
% 'HMR_2447',...
% 'HMR_1186',...
% 'HMR_1320',...
% 'HMR_2443',...
% 'HMR_7265',...
% 'HMR_2558',...
% 'HMR_3288',...
% 'HMR_3316',...
% 'HMR_0579',...
% 'HMR_0597',...
% 'HMR_0598',...
% 'HMR_0599',...
% 'HMR_0600',...
% 'HMR_0601',...
% 'HMR_0602',...
% 'HMR_0625',...
% 'HMR_0763',...
% 'HMR_3522',...
% 'HMR_6813',...
% 'HMR_2581',...
% 'HMR_2582',...
% 'HMR_1388',...
% 'HMR_7255',...
% 'HMR_0582',...
% 'HMR_0586',...
% 'HMR_0673',...
% 'HMR_3526',...
% 'HMR_4767',...
% 'HMR_0580',...
% 'HMR_0589',...
% 'HMR_0590',...
% 'HMR_0591',...
% 'HMR_0592',...
% 'HMR_0593',...
% 'HMR_0594',...
% 'HMR_0632',...
% 'HMR_3527',...
% 'HMR_7614',...
% 'HMR_0733',...
% 'HMR_0758',...
% 'HMR_0750',...
% 'HMR_8218',...
% 'HMR_0588',...
% 'HMR_7271',...
% 'HMR_1067',...
% 'HMR_1070',...
% 'HMR_6435',...
% 'HMR_6451',...
% 'HMR_1730',...
% 'HMR_1729',...
% 'HMR_9726',...
% 'HMR_2660',...
% 'HMR_2662',...
% 'HMR_2824',...
% 'HMR_3228',...
% 'HMR_3344',...
% 'HMR_6692',...
% 'HMR_3258',...
% 'HMR_6702',...
% 'HMR_6703',...
% 'HMR_3343',...
% 'HMR_3264',...
% 'HMR_3256',...
% 'HMR_6691',...
% 'HMR_1066',...
% 'HMR_6433',...
% 'HMR_6448',...
% 'HMR_6471',...
% 'HMR_6473',...
% 'HMR_6484',...
% 'HMR_6488',...
% 'HMR_6434',...
% 'HMR_6450',...
% 'HMR_1302',...
% 'HMR_6472',...
% 'HMR_6486',...
% 'HMR_6704',...
% 'HMR_6705',...

