IEMs={'Tangier disease'	'19'
    %	'early onset bilateral and multifocal clear cell renal carcinoma'	'2272'
    %	'hereditary megaloblastic anemia 1 (MGA1)'	'8029'
    '1)Diabetes mellitus, insulin-resistant, with acanthosis nigricans,  2)Hyperinsulinemic hypoglycemia, familial, 5,   3)Leprechaunism and   4)Rabson-Mendenhall syndrome'	'3643'
    '21-hydroxylase deficiency'	'1589'
    '2-hydroxyglutaric aciduria'	'728294'
    '2-hydroxyglutaric aciduria'	'79944'
    '3-beta (?)-hydroxysteroid dehydrogenase (HSD) deficiency'	'3284'
    '3beta-hydroxy-Delta(5)-C(27)-steroid oxidoreductase defect'	'80270'
    '3-methylcrotonyl coA carboxylase deficiency'	'56922'
    '3-methylcrotonyl coA carboxylase deficiency'	'64087'
    '3-methylglutaconic aciduria type I'	'549'
    '3-methylglutaconic aciduria type II (Barth syndrome)'	'6901'
    %	'3-methylglutaconic aciduria type III'	'80207'
    '3-methylglutaconic aciduria type V'	'131118'
    '5-alpha reductase deficiency'	'6716'
    %	'6-mercaptopurine sensitivity'	'7172'
    %	'Abetalipoproteinemia'	'4547'
    %	'Abetalipoproteinemia'	'4547'
    'acatalasemia'	'847'
    'Acetyl-CoA carboxylase deficiency'	'31'
    'Acute intermittent porphyria'	'3145'
    'Adenine phosphoribosyltransferase deficiency'	'353'
    'Adenosine deaminase (ADA) deficiency'	'100'
    'adenylosuccinase deficiency'	'158'
    'adrenal hyperplasia type 5 (AH5)'	'1586'
    'AICA-ribosiduria'	'471'
    'Alkaptonuria'	'3081'
    'Allan-Herndon-Dudley syndrome'	'6567'
    %	'Alpha thalassemia'	'3039'
    %	'Alpha thalassemia'	'3040'
    %	'Alpha thalassemia X-linked mental retardation syndrome'	'546'
    'Alpha-ketoglutarate dehydrogenase deficiency'	'4967'
    'Alpha-mannosidosis'	'4125'
    'Aminoacylase 1 deficiency'	'95'
    %	'Androgen insensitivity syndrome'	'367'
    %	'Angelman syndrome'	'7337'
    %	'Apnea, postanesthetic'	'590'
    'apoC-II deficiency'	'344'
    'apolipoprotein A-II deficiency or hypercholesterolemia'	'336'
    %	'Apolipoprotein H deficiency'	'350'
    'Arginase deficiency'	'383'
    'arginine:glycine amidinotransferase deficiency'	'2628'
    'Argininosuccinic aciduria'	'435'
    'aromatase deficiency'	'1588'
    'Aromatic L-amino acid decarboxylase  deficiency'	'1644'
    'Aspartylglucosaminuria'	'175'
    'Asthma'	'3176'
    %	'Ataxia with vitamin E deficiency'	'7274'
    'autosomal dominant hypercarotenemia and vitamin A deficiency'	'53630'
    'autosomal dominant hypophosphatemic rickets (ADHR)'	'5251'
    'autosomal dominant hypophosphatemic rickets (ADHR)'	'8074'
    %	'Bartter syndrome type 4A (BS4A) with sensorineural deafness'	'7809'
    'Bartter syndrome, type 1'	'6557'
    'Berardinelli-Seip congenital lipodystrophy type 1'	'10555'
    'Berardinelli-Seip congenital lipodystrophy type 2'	'26580'
    %	'Bernard-Soulier syndrome type A'	'2811'
    %	'Bernard-Soulier syndrome type B'	'2812'
    %	'Bernard-Soulier syndrome type C'	'2815'
    %	'Beta-globin type methemoglobinemia and Sickle cell disease and Beta thalassemia'	'3043'
    'Beta-ketothiolase deficiency'	'38'
    'Beta-mannosidosis'	'4126'
    'Biotinidase deficiency'	'686'
    'Brugada syndrome type 2 (BRS2) and sudden infant death syndrome (SIDS)'	'23171'
    'Brunner syndrome (BRUNS)'	'4128'
    'Canavan disease'	'443'
    'Carbamoyl phosphate synthetase I deficiency'	'1373'
    'Carbohydrate-deficient glycoprotein syndrome, type Ib'	'4351'
    %	'Carboxylesterase 1 deficiency'	'1066'
    'carnitine acylcarnitine translocase deficiency'	'788'
    'Cerebrotendinous xanthomatosis'	'1593'
    %	'Chediak-Higashi syndrome'	'1130'
    'Cholesteryl ester storage disease'	'3988'
    'Cholesteryl ester storage disease'	'3988'
    'chronic granulomatous disease (CGD) type I'	'653361'
    'Chylomicron retention disease'	'51128'
    'Classic galactosemia/type 1'	'2592'
    'classic refsum disease'	'5264'
    'combined deficiency of vitamin K-dependent clotting factors type 2 (VKCFD2)'	'79001'
    %	'Complement factor I deficiency'	'3426'
    'congenital adrenal hyperplasia'	'1584'
    'congenital disorder of glycosylation type 1E (CDG1E)'	'8813'
    'Congenital disorder of glycosylation type Ia'	'5373'
    'congenital disorder of glycosylation type Id'	'10195'
    'Congenital disorder of glycosylation, type Ic'	'29929'
    'congenital erythropoietic porphyria/Gunther disease'	'7390'
    'Congenital hypothyroidism'	'50506'
    'Congenital hypothyroidism'	'7849'
    'Congenital hypothyroidism'	'6528'
    'Congenital hypothyroidism'	'7038'
    'Congenital hypothyroidism'	'7173'
    'Congenital hypothyroidism'	'7253'
    'Congenital hypothyroidism'	'7252'
    'Congenital hypothyroidism'	'50506'
    'Congenital hypothyroidism'	'7173'
    'Congenital lactase deficiency/congenital alactasia'	'3938'
    'congenital lipoid adrenal hyperplasia (CLAH)/ StAR DEFICIENCY'	'1583'
    'Congenital sucrase-isomaltase deficiency'	'6476'
    'Conradi-Hunermann syndrome'	'10682'
    'corticosterone methyloxidase type 1 deficiency (CMO-1 deficiency)/aldosterone deficiency due to defect in 18-hydroxylase/aldosterone deficiency I'	'1585'
    'CPT-1 deficiency'	'1374'
    'CPT-2 deficiency'	'1376'
    'Cranioosteoarthropathy,Digital clubbing, isolated congenital and Hypertrophic osteoarthropathy, primary, autosomal recessive'	'3248'
    'Crigler-Najjar syndrome type I/Gilbert syndrome/Crigler-Najjar syndrome type II'	'54658'
    'Cystathioninuria'	'1491'
    %	'Cystic fibrosis'	'1080'
    'Cystinosis'	'1497'
    'Cystinuria'	'6519'
    'Cystinuria'	'11136'
    'Cytochrome P450 oxidoreductase deficiency'	'5447'
    'cytosolic phosphoenolpyruvate carboxykinase deficiency '	'5105'
    'D-bifunctional protein deficiency (DBPD)'	'3295'
    'delta-aminolevulinate dehydratase deficiency'	'210'
    'Deoxyguanosine kinase deficiency'	'1716'
    'desmosterolosis'	'1718'
    %	'D-glyceric acidemia'	'132158'
    'dicarboxylic aminoaciduria'	'6505'
    'Dihydrofolate reductase deficiency'	'1719'
    'Dihydropyrimidinuria'	'1807'
    'Dihyropyrimidine dehydrogenase deficiency'	'1806'
    'Donnai-Barrow syndrome'	'4036'
    'Dubin-Johnson syndrome'	'1244'
    %	'Duchenne and Becker types of muscular dystrophy'	'1756'
    'Ehlers-Danlos syndrome'	'9509'
    'Ehlers-Danlos syndrome'	'1277'
    'Ehlers-Danlos syndrome'	'1278'
    'Ehlers-Danlos syndrome'	'1281'
    'Ehlers-Danlos syndrome'	'1289'
    'Ehlers-Danlos syndrome'	'1290'
    'Ehlers-Danlos syndrome'	'7148'
    'Ehlers-Danlos syndrome'	'5351'
    'emphysema or liver disease'	'5265'
    'emphysema or liver disease'	'5265'
    'enterokinase deficiency'	'5651'
    'erythrocyte AMP deaminase deficiency'	'272'
    'essential hypertension'	'5740'
    'essential pentosuria'	'51181'
    'Ethylmalonic encephalopathy'	'23474'
    'Exertional myoglobinuria due to deficiency of LDH-A/Glycogen storage disease XI'	'3939'
    'Fabry disease'	'2717'
    'familial hypercholanemia (FHCA)'	'570'
    'familial hypercholesterolemia'	'2053'
    'Familial hypercholesterolemia'	'3949'
    'Familial hypercholesterolemia'	'26119'
    'Familial hypercholesterolemia'	'255738'
    'Familial hypercholesterolemia'	'338'
    'Familial hyperinsulinism (FHI)'	'6833'
    'Familial hyperinsulinism (FHI)'	'3767'
    'Familial hyperinsulinism (FHI)'	'2746'
    'Familial hyperinsulinism (FHI)'	'2645'
    'Familial hyperinsulinism (FHI)'	'3033'
    'familial intrahepatic cholestasis-1 (PFIC1)'	'5205'
    'Familial lipoprotein lipase deficiency'	'4023'
    %	'Familial Mediterranean fever with nephropathy'	'4210'
    'Fanconi renotubular syndrome'	'6569'
    'Fanconi-Bickel syndrome'	'6514'
    'Farber lipogranulomatosis'	'427'
    'fish-eye disease/ LCAT deficiency'	'3931'
    'Friedreich ataxia'	'2395'
    'fructose-1,6-bisphosphatase deficiency'	'2203'
    'Fructosuria(essential Fructosuria)'	'3795'
    'Fucosidosis'	'2517'
    'fumarase deficiency'	'2271'
    'Galactosemia type II '	'2584'
    'Galactosemia type III'	'2582'
    'Galactosialidosis'	'5476'
    'Gamma-glutamylcysteine synthetase deficiency'	'2729'
    'Gaucher disease'	'2629'
    'glanzmann?s thrombasthenia'	'3690'
    'glanzmann?s thrombasthenia'	'3674'
    'Glucose-6-phosphate dehydrogenase deficiency'	'2539'
    'Glucose-galactose malabsorption'	'6523'
    'GLUT1 deficiency syndrome'	'6513'
    'Glutamate formiminotransferase deficiency'	'10841'
    'glutaric acidemia type I.'	'2639'
    'Glutaric acidemia type II'	'2108'
    'Glutaric acidemia type II'	'2109'
    'Glutaric acidemia type II'	'2110'
    'glutaric aciduria type III'	'79783'
    'Glutathione synthetase deficiency and 5-oxoprolinuria'	'2937'
    'glycerol kinase deficiency'	'2710'
    'Glycine encephalopathy/ nonketotic hyperglycinemia / NKH'	'275'
    'Glycine encephalopathy/ nonketotic hyperglycinemia / NKH'	'2731'
    'Glycogen storage disease 0, muscle/muscle glycogen synthase deficiency'	'2997'
    'Glycogen storage disease I'	'2538'
    'Glycogen storage disease I'	'2542'
    'Glycogen storage disease IIIa/Glycogen storage disease IIIb/CORI DISEASE'	'178'
    'Glycogen storage disease Ixc'	'5261'
    'glycogen storage disease type 0 (GSD0)/liver glycogen synthase deficiency'	'2998'
    'glycogen storage disease type 13 (GSD13)'	'2027'
    'glycogen storage disease type 6/Hers disease'	'5836'
    'glycogen storage disease type 9A'	'5256'
    'Glycogen storage disease type II/Pompe disease'	'2548'
    'Glycogen storage disease type IV/Andersen?s disease'	'2632'
    'Glycogen storage disease type V/McArdle disease'	'5837'
    'Glycogen storage disease VII/Tarui disease'	'5213'
    'Glycogen storage disease X'	'5224'
    'Glycogen storage disease XII/Aldolase A deficiency'	'226'
    'Glycogen storage disease XIV'	'5236'
    'GM1-gangliosidosis and Mucopolysaccharidosis type IV type B'	'2720'
    'GM2-gangliosidosis, AB variant'	'2760'
    %	'GRACILE syndrome'	'617'
    'Guanidinoacetate methyltransferase deficiency'	'2593'
    'Gyrate atrophy of the choroid and retina'	'4942'
    'hartnup disorder'	'340024'
    'Hemochromatosis'	'57817'
    'Hemochromatosis'	'3077'
    'Hemochromatosis'	'148738'
    'Hemochromatosis'	'7036'
    'Hemochromatosis'	'30061'
    'Hemolytic anemia due to adenylate kinase deficiency'	'203'
    'Hemophilia A'	'2157'
    'hemophilia B'	'2158'
    'hepatic lipase deficiency'	'3990'
    'Hereditary angioedema'	'710'
    'Hereditary angioedema'	'2161'
    'Hereditary coproporphyria'	'1371'
    'Hereditary folate malabsorption'	'113235'
    'hereditary fructose intolerance'	'229'
    'Hereditary spherocytosis type 1'	'286'
    'hereditary spherocytosis type 2'	'6710'
    'hereditary spherocytosis-3'	'6708'
    'hereditary spherocytosis-4'	'6521'
    'hereditary spherocytosis-4'	'6521'
    'hereditary spherocytosis-5'	'2038'
    'Hermansky-Pudlak syndrome'	'3257'
    'Hermansky-Pudlak syndrome'	'84343'
    'High density lipoprotein cholesterol level QTL'	'5360'
    'Histidinemia'	'3034'
    'HMG-CoA lyase deficiency'	'3155'
    'HMG-CoA synthase-2 deficiency'	'3158'
    'Holocarboxylase synthetase deficiency'	'3141'
    'Homocysteine plasma level'	'4837'
    'Homocystinuria'	'875'
    'Homocystinuria'	'4524'
    'Homocystinuria'	'4548'
    'Hyperapobetalipoproteinemia'	'5465'
    'Hyperkalemic periodic paralysis'	'6329'
    'Hyperlysinemia I, familial'	'10157'
    'Hyperlysinemia I, familial'	'10157'
    'Hypermethioninemia'	'191'
    'Hypermethioninemia'	'27232'
    'Hypermethioninemia'	'4143'
    'hyperphosphatemic familial tumoral calcinosis (HFTC)'	'2591'
    'Hyperprolinemia type I'	'5625'
    'Hyperprolinemia type II'	'8659'
    'Hypokalemic periodic paralysis'	'779'
    'Hypokalemic periodic paralysis'	'6329'
    'Hypophosphatasia'	'249'
    %	'ichthyosis lamellar type 3 (LI3)'	'126410'
    'ichthyosis prematurity syndrome (IPS)'	'10999'
    'Imerslund-Grasbeck syndrome'	'8029'
    'Imerslund-Grasbeck syndrome'	'81693'
    'iminoglycinuria'	'153201'
    'iminoglycinuria'	'54716'
    'iminoglycinuria'	'340024'
    'Infantile neuroaxonal dystrophy'	'8398'
    'Inherited thyroxine-binding globulin deficiency'	'6906'
    'insulin resistance and various other metabolic disorders'	'23452'
    'Isobutyryl-coenzyme A (CoA) dehydrogenase (IBD)'	'27034'
    'Isovaleric acidemia'	'3712'
    'Juvenile Batten disease'	'1201'
    'keratosis follicularis spinulosa decalvans (KFSD)'	'6303'
    'Krabbe disease'	'2581'
    'Kufs disease'	'5538'
    'Lactose intolerance in adulthood'	'3938'
    'Lactose intolerance in adulthood'	'4175'
    'Lathosterolosis'	'6309'
    'Leber congenital amaurosis type 3'	'145226'
    'Lesch-Nyhan syndrome'	'3251'
    'leukotriene C4 synthase deficiency (LTC4 synthase deficiency)'	'4056'
    'LONG-CHAIN-3-HYDROXYACYL-CoA DEHYDROGENASE DEFICIENCY (LCHAD)'	'3032'
    'Lowe syndrome'	'4952'
    'Lysinuric protein intolerance'	'9056'
    'Malonyl-coenzyme A (CoA) decarboxylase deficiency'	'23417'
    'maple syrup urine disease'	'593'
    'maple syrup urine disease'	'594'
    'maple syrup urine disease'	'1629'
    'maple syrup urine disease'	'1738'
    'Marfan syndrome type 1, isolated ectopia lentis, autosomal dominant Weill-Marchesani syndrome, MASS syndrome, and Shprintzen-Goldberg craniosynostosis syndrome. '	'2200'
    'Marfan Syndrome type 2, Loeys-Deitz Aortic Aneurysm Syndrome'	'7048'
    'medium chain acyl coA dehydrogenase deficiency'	'34'
    'Menkes syndrome'	'538'
    'Metachromatic leukodystrophy'	'410'
    'Metachromatic leukodystrophy'	'410'
    'Metachromatic leukodystrophy'	'5660'
    'methylmalonic acidemia (MMA)'	'166785'
    'methylmalonic acidemia (MMA)'	'4594'
    'methylmalonic aciduria (cobalamin deficiency) cblD type'	'27249'
    'methylmalonic aciduria and homocystinuria type cblC.'	'25974'
    'Methylmalonic aciduria III'	'84693'
    'mevalonic aciduria'	'4598'
    'milder variant of X-linked adrenoleukodystrophy'	'11001'
    'Mitochondrial encephalomyopathy, lactic acidosis, and stroke-like episodes (MELAS)'	'4535'
    'Mitochondrial encephalomyopathy, lactic acidosis, and stroke-like episodes (MELAS)'	'4540'
    'Mitochondrial encephalomyopathy, lactic acidosis, and stroke-like episodes (MELAS)'	'4564'
    'Mitochondrial encephalomyopathy, lactic acidosis, and stroke-like episodes (MELAS)'	'4567'
    'Mitochondrial encephalomyopathy, lactic acidosis, and stroke-like episodes (MELAS)'	'4577'
    'Mitochondrial neurogastrointestinal encephalopathy (MNGIE) disease'	'1890'
    'mitochondrial phosphoenolpyruvate carboxykinase deficiency '	'5106'
    'Mitochondrial trifunctional protein deficiency'	'3030'
    'Mitochondrial trifunctional protein deficiency'	'3032'
    'Molybdenum cofactor deficiency, type A'	'4337'
    'Molybdenum cofactor deficiency, type B'	'4338'
    'Mucolipidosis II alpha/beta (also known as I-cell disease)'	'79158'
    'Mucolipidosis III gamma'	'84572'
    'Mucolipidosis type IV'	'57192'
    'mucopolysaccharidosis IIIA'	'6448'
    'Mucopolysaccharidosis type I '	'3425'
    'Mucopolysaccharidosis type II/Hunter syndrome'	'3423'
    'mucopolysaccharidosis type III C'	'138050'
    'Mucopolysaccharidosis type III D/Sanfilippo syndrometype III D'	'2799'
    'mucopolysaccharidosis type IIIB/Sanfilippo syndrome B'	'4669'
    'Mucopolysaccharidosis type IV type A/Morquio syndrome'	'2588'
    'Mucopolysaccharidosis type VI/Maroteaux-Lamy syndrome'	'411'
    'Mucopolysaccharidosis type VII/ Sly syndrome'	'2990'
    'multiple lipid transport defects'	'29881'
    'Muscle glycogenosis/ glycogen storage disease type 9D (GSD9D)'	'5255'
    'myeloperoxidase deficiency'	'4353'
    'myoadenylate deaminase deficiency'	'270'
    'Myotonic dystrophy type 1'	'1760'
    'Myotonic dystrophy type 2'	'7555'
    'N-acetylglutamate synthase deficiency'	'162417'
    'neonatal onset insulin-dependent diabetes mellitus,Immune dysregulation, polyendocrinopathy, enteropathy, X-linked (IPEX) syndrome'	'50943'
    'Nephrogenic diabetes insipidus'	'554'
    'Nephrogenic diabetes insipidus'	'359'
    'Neuropathy, ataxia, and retinitis pigmentosa (NARP)'	'4508'
    'Neutral lipid storage disease'	'57104'
    'Niemann-Pick disease'	'4864'
    'Niemann-Pick disease'	'6609'
    'Niemann-Pick disease'	'10577'
    'nonspherocytic hemolytic anemia'	'3098'
    'obesity and pituitary dysfunction. '	'3953'
    'obesity in middle age.'	'133522'
    'Ocular albinism'	'4935'
    'Oculocutaneous albinism'	'4948'
    'Oculocutaneous albinism'	'51151'
    'Oculocutaneous albinism'	'7306'
    'Oculocutaneous albinism'	'7299'
    'Optic atrophy type 1'	'4976'
    'Ornithine transcarbamylase deficiency'	'5009'
    'Ornithine translocase deficiency/HHH (hyperornithinemia, hyperammonemia, homocitrullinuria) syndrome.'	'10166'
    'orotic aciduria'	'7372'
    'oxysterol 7-alphahydroxylase deficiency'	'51302'
    'Parkinsonism, susceptibility/Codeine sensitivity/Debrisoquine sensitivity'	'1565'
    'phenylketonuria'	'5053'
    'Phospholipase A2, group IV A, deficiency'	'5321'
    'Phosphoribosylpyrophosphate synthetase superactivity (PRS superactivity)'	'5631'
    'Polycythemia vera'	'3717'
    'Polycythemia vera'	'54790'
    'Porphyria'	'212'
    'Porphyria'	'2235'
    'Porphyria cutanea tarda (PCT)'	'7389'
    'Primary congenital glaucoma '	'1545'
    'Primary congenital glaucoma '	'4653'
    'Primary hyperoxaluria-type 1'	'189'
    'Progressive familial intrahepatic cholestasis (PFIC)'	'8647'
    'Progressive familial intrahepatic cholestasis (PFIC)'	'5244'
    'Prolidase deficiency'	'5184'
    'propionic acidemia'	'5095'
    'propionic acidemia'	'5096'
    'pseudohypoparathyroidism type Ia'	'2778'
    'pseudoneonatal adrenoleukodystrophy'	'51'
    'pseudo-Zellweger syndrome'	'30'
    'pulmonary surfactant metabolism dysfunction type 2 '	'6440'
    'pulmonary surfactant metabolism dysfunction type 3 (SMDP3)'	'21'
    'purine nucleoside phosphorylase deficiency'	'4860'
    'Pyridoxal 5-phosphate-dependent epilepsy'	'55163'
    'Pyruvate carboxylase deficiency'	'5091'
    'pyruvate dehydrogenase (PDH) complex deficiency'	'8050'
    'pyruvate kinase deficiency'	'5313'
    'renal glucosuria'	'6524'
    %	'Renal glucosuria associated with juvenile cataract with microcornea'	'387700'
    'renal tubular acidosis (RTA) '	'525'
    'Renal tubular acidosis, distal, autosomal recessive'	'50617'
    'Renal tubular acidosis, distal, autosomal recessive'	'50617'
    'reticular dysgenesis (RDYS)/aleukocytosis'	'204'
    'Rhizomelic chondrodysplasia punctata type 1'	'5191'
    'Rhizomelic chondrodysplasia punctata type 1'	'8540'
    'Rhizomelic chondrodysplasia punctata type 1'	'8443'
    'Rhizomelic chondrodysplasia punctata type 2'	'8443'
    'Rhizomelic chondrodysplasia punctata, type 3'	'8540'
    'Ribose 5-phosphate isomerase deficiency'	'22934'
    %	'rickets vitamin D-dependent type 1B (VDDR1B)/pseudovitamin D(3) deficiency rickets due to 25-hydroxylase deficiency'	'120227'
    'rickets vitamin D-dependent type 2A (VDDR2A)'	'7421'
    'Sandhoff disease'	'3074'
    'Sarcosinemia'	'1757'
    'Schindler disease'	'4668'
    'short chain 3-hydroxy acyl coA dehydrogenase deficiency, Familial hyperinsulinism (FHI)'	'3033'
    'short chain acyl coA dehydrogenase deficiency'	'35'
    'Sialic acid storage disease'	'26503'
    'Sialidosis'	'4758'
    'Sialuria'	'10020'
    'sitosterolemia'	'64241'
    'sitosterolemia'	'64240'
    'Sjoegren-Larsson syndrome'	'224'
    'Smith-Lemli-Opitz syndrome'	'1717'
    'Snyder-Robinson syndrome'	'6611'
    'Succinate-coenzyme A (CoA) ligase deficiency/LACTIC ACIDOSIS, FATAL INFANTILE'	'8803'
    'Succinate-coenzyme A (CoA) ligase deficiency/LACTIC ACIDOSIS, FATAL INFANTILE'	'8802'
    'Succinic semialdehyde dehydrogenase deficiency'	'7915'
    'succinyl-CoA:3-oxoacid CoA transferase deficiency'	'5019'
    'SUCLA2-Related Mitochondrial DNA Depletion Syndrome, Encephalomyopathic Form, with Mild Methylmalonic Aciduria'	'8803'
    'SUMF1 disease/ multiple sulfatase deficiency'	'285362'
    'surfactant protein B deficiency/pulmonary alveolar proteinosis'	'6439'
    'systemic carnitine deficiency'	'6584'
    'Tay-Sachs disease'	'3073'
    'Tetrahydrobiopterin deficiency'	'2643'
    'Tetrahydrobiopterin deficiency'	'5092'
    'Tetrahydrobiopterin deficiency'	'5805'
    'Tetrahydrobiopterin deficiency'	'5860'
    'thromboxane synthetase deficiency'	'6916'
    'transaldolase deficiency'	'6888'
    'Transthyretin amyloidos'	'7276'
    'Transthyretin amyloidos'	'7276'
    'TRIFUNCTIONAL PROTEIN DEFICIENCY'	'3030'
    'Trimethylaminuria'	'2328'
    'Type 2 primary hyperoxaluria '	'9380'
    'type 3 hyperlipoproteinemia'	'348'
    'Type I citrullinemia'	'445'
    'Type II citrullinemia'	'10165'
    'Type II citrullinemia'	'10165'
    %	'type V hyperlipoproteinemia'	'116519'
    'Tyrosinemia type 1'	'2184'
    'tyrosinemia type II'	'6898'
    'Tyrosinemia type III'	'3242'
    'Tyrosinemia, type Ib'	'2954'
    'urocanic aciduria'	'131669'
    'Variegate porphyria'	'5498'
    'Very long-chain acyl-coenzyme A dehydrogenase (VLCAD) deficiency'	'37'
    'Very long-chain acyl-coenzyme A dehydrogenase (VLCAD) deficiency '	'37'
    'von Willebrand disease (VWD) type 1 '	'7450'
    'Wilson disease'	'540'
    'Wilson disease'	'5621'
    'Wolff-Parkinson-White syndrome'	'51422'
    'xanthinuria type 1'	'7498'
    'Xeroderma pigmentosum'	'2068'
    'Xeroderma pigmentosum'	'2071'
    'Xeroderma pigmentosum'	'5429'
    'Xeroderma pigmentosum'	'7508'
    'Xeroderma pigmentosum'	'7507'
    'X-linked adrenoleukodystrophy'	'215'
    'X-linked adrenoleukodystrophy'	'215'
    'X-linked adrenoleukodystrophy'	'225'
    'X-linked agammaglobulinemia (XLA)'	'695'
    'X-linked chronic granulomatous disease (CGD)'	'1536'
    'X-linked ichthyosis'	'412'
    'ZAP70-related severe combined immunodeficiency'	'7535'
    'Zellweger syndrome'	'1962'
    'Zellweger syndrome'	'5825'
    'Zellweger syndrome and Leukoencephalopathy with dystonia and motor neuropathy'	'6342'
    };