% conservedMoietyHotspotsCheck.m
%
% Non-CI reproducibility check and benchmark for feature
% 20260929-111453-conserved-moiety-table-hotspots (tasks.md T006; spec FR-002, FR-009,
% SC-001 to SC-004; research R1, R7).
%
% On the 1,960-reaction lowSymmetryRisk_2000rxn model (conserved moieties only, sanityChecks 0):
%   1. runs the current identifyConservedReactingMoieties and compares arm, moietyFormulae and
%      reacting with the golden run of feature 20260928-100409 (isequaln), whose outputs equal
%      those of commit 858feabc1;
%   2. counts, under the profiler, the graph.subgraph, graph.subsasgn and
%      extractPartitionSubgraphs calls made from identifyConservedReactingMoieties (SC-002);
%   3. unless CBT_CMH_NO_TIMING=1: times the pre-change copy and the current function back to
%      back (alternating, CBT_CMH_TIMING_RUNS runs each, default 3) and checks the SC-003 gate
%      (median ratio <= 0.65); then benchmarks each block on its own (SC-004, reported);
% and appends the results to conservedMoietyHotspotsResults.md.
%
% USAGE (headless, after initCobraToolbox):
%   setenv('CBT_CMH_NO_TIMING', '1');   % optional: equality and call counts only
%   setenv('CBT_CMH_TIMING_ONLY', '1'); % optional: skip sections 1-2 (re-measure timing only)
%   run('/home/jackmcgoldrick/cobratoolbox/specs/20260929-111453-conserved-moiety-table-hotspots/conservedMoietyHotspotsCheck.m')

featureDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(fileparts(featureDir));
addpath(featureDir);   % identifyConservedReactingMoietiesBaseline
srcPath = which('identifyConservedReactingMoieties');
homeDir = char(java.lang.System.getProperty('user.home'));
outputsDir = fullfile(homeDir, 'repos', 'reconXmoieties', 'experiments', 'moietySizing', ...
    'results', 'outputs');
extDir = fullfile(outputsDir, 'conservedMoietyHotspots');
resultsPath = fullfile(featureDir, 'conservedMoietyHotspotsResults.md');

[~, gitCommit] = system(sprintf('git -C "%s" rev-parse --short HEAD', repoRoot));
[~, gitDirty] = system(sprintf('git -C "%s" status --porcelain -- src', repoRoot));
srcState = strtrim(gitCommit);
if ~isempty(strtrim(gitDirty))
    srcState = [srcState '+modified'];
end
runTime = char(datetime('now', 'TimeZone', 'UTC', 'Format', 'yyyy-MM-dd HH:mm'));
if ~isfile(resultsPath)
    fid = fopen(resultsPath, 'w');
    fprintf(fid, ['# Results: table hotspots in `identifyConservedReactingMoieties`\n\n' ...
        'Feature `20260929-111453-conserved-moiety-table-hotspots`. Base commit `858feabc1`. ' ...
        'Generated by `conservedMoietyHotspotsCheck.m`; append-only.\n']);
    fclose(fid);
end

inputs = load(fullfile(extDir, 'n1960-identifyInputs.mat'), 'model', 'BG', 'dATM');
options = struct('sanityChecks', 0, 'conservedMoietiesOnly', true);

timingOnly = strcmp(getenv('CBT_CMH_TIMING_ONLY'), '1');
isIdentical = true;
if ~timingOnly
%% 1. equality with the golden run (FR-002, SC-001)
[arm, moietyFormulae, reacting] = identifyConservedReactingMoieties(inputs.model, inputs.BG, ...
    inputs.dATM, options);
golden = load(fullfile(outputsDir, 'extractBondSubgraphsPeeling', 'n1960-endToEnd-golden.mat'), ...
    'arm', 'moietyFormulae', 'reacting');
sameArm = isequaln(arm, golden.arm);
sameFormulae = isequaln(moietyFormulae, golden.moietyFormulae);
sameReacting = isequaln(reacting, golden.reacting);
differingArmFields = {};
if ~sameArm
    armFields = fieldnames(golden.arm);
    for f = 1:numel(armFields)
        if ~isfield(arm, armFields{f}) || ~isequaln(arm.(armFields{f}), golden.arm.(armFields{f}))
            differingArmFields{end + 1} = armFields{f}; %#ok<SAGROW>
        end
    end
end
clear arm moietyFormulae reacting golden
isIdentical = sameArm && sameFormulae && sameReacting;

%% 2. profiler call counts (SC-002)
profile clear
profile on
identifyConservedReactingMoieties(inputs.model, inputs.BG, inputs.dATM, options);
profile off
profileInfo = profile('info');
functionTable = profileInfo.FunctionTable;
counts = struct('subgraph', 0, 'subsasgn', 0, 'extractPartitionSubgraphs', 0);
for r = 1:numel(functionTable)
    if ~strcmp(functionTable(r).FileName, srcPath)
        continue
    end
    for c = 1:numel(functionTable(r).Children)
        childName = functionTable(functionTable(r).Children(c).Index).FunctionName;
        nCalls = functionTable(r).Children(c).NumCalls;
        switch childName
            case 'graph.subgraph'
                counts.subgraph = counts.subgraph + nCalls;
            case 'graph.subsasgn'
                counts.subsasgn = counts.subsasgn + nCalls;
            case 'extractPartitionSubgraphs'
                counts.extractPartitionSubgraphs = counts.extractPartitionSubgraphs + nCalls;
        end
    end
end
% propagation block line times (SC-004 source for FR-004a), found by its comment lines
srcLines = splitlines(fileread(srcPath));
blockStart = find(startsWith(strtrim(srcLines), '%assign the moiety indices by using the indices'), 1);
blockEnd = find(startsWith(strtrim(srcLines), '%extract the map from atoms to moiety'), 1);
propagationSeconds = NaN;
mainRow = find(strcmp({functionTable.FileName}, srcPath) & ...
    strcmp({functionTable.FunctionName}, 'identifyConservedReactingMoieties'), 1);
if ~isempty(mainRow) && ~isempty(blockStart) && ~isempty(blockEnd)
    executed = functionTable(mainRow).ExecutedLines;
    inBlock = executed(:, 1) >= blockStart & executed(:, 1) < blockEnd;
    propagationSeconds = sum(executed(inBlock, 3));
end

fid = fopen(resultsPath, 'a');
fprintf(fid, ['\n### Equality and call counts, %s UTC, source %s\n\n' ...
    '- n1960 (conserved-only): arm %s, moietyFormulae %s, reacting %s%s\n' ...
    '- Calls from `identifyConservedReactingMoieties` (profiled): graph.subgraph %d, ' ...
    'graph.subsasgn %d, extractPartitionSubgraphs %d\n' ...
    '- Propagation block (lines %d-%d) profiled line time: %.1f s\n'], runTime, srcState, ...
    yesNo(sameArm), yesNo(sameFormulae), yesNo(sameReacting), ...
    ternary(isempty(differingArmFields), '', [' (arm fields differing: ' strjoin(differingArmFields, ', ') ')']), ...
    counts.subgraph, counts.subsasgn, counts.extractPartitionSubgraphs, blockStart, blockEnd - 1, ...
    propagationSeconds);
fclose(fid);
fprintf('identical %d; subgraph %d, subsasgn %d, extractPartitionSubgraphs %d; propagation %.1f s\n', ...
    isIdentical, counts.subgraph, counts.subsasgn, counts.extractPartitionSubgraphs, propagationSeconds);
end

%% 3. timing (SC-003 gate) and block micro-benchmark (SC-004)
sc003Failed = false;
if ~strcmp(getenv('CBT_CMH_NO_TIMING'), '1')
    nRuns = 3;
    if ~isempty(getenv('CBT_CMH_TIMING_RUNS'))
        nRuns = str2double(getenv('CBT_CMH_TIMING_RUNS'));
    end
    baselineSeconds = zeros(nRuns, 1);
    newSeconds = zeros(nRuns, 1);
    for run = 1:nRuns
        tStart = tic;
        identifyConservedReactingMoietiesBaseline(inputs.model, inputs.BG, inputs.dATM, options);
        baselineSeconds(run) = toc(tStart);
        tStart = tic;
        identifyConservedReactingMoieties(inputs.model, inputs.BG, inputs.dATM, options);
        newSeconds(run) = toc(tStart);
        fprintf('timing run %d: baseline %.1f s, new %.1f s\n', run, baselineSeconds(run), newSeconds(run));
    end
    ratio = median(newSeconds) / median(baselineSeconds);
    sc003Failed = ratio > 0.65;
    blocks = benchmarkBlocks(fullfile(outputsDir, 'extractBondSubgraphsPeeling', 'n1960-inputs.mat'));
    fid = fopen(resultsPath, 'a');
    fprintf(fid, ['\n### Timing, %s UTC, source %s, %d alternating runs each' ...
        ternary(timingOnly, ' (timing only; equality not re-checked in this run)', '') '\n\n' ...
        '- Baseline runs: %s s; new runs: %s s\n' ...
        '- **SC-003 (gate)**: median new/baseline = %.1f / %.1f = %.3f (limit 0.65): %s\n' ...
        '- **SC-004 (reported)**, blocks on the real n1960 ATG (captured at the extractBondSubgraphs call):\n' ...
        '  - reorientation (19,952 edges): old %.2f s, new %.2f s, ratio %.3f, identical %s\n' ...
        '  - component subgraphs, one set: old %.1f s, new %.1f s, ratio %.3f, identical %s\n' ...
        '  - moiety graphs (stand-in partition by component, %d parts): old %.1f s, new %.1f s, ratio %.3f, identical %s\n' ...
        '  - propagation: see the profiled line time above (compare with the unchanged-source entry)\n'], ...
        runTime, srcState, nRuns, mat2str(baselineSeconds', 4), mat2str(newSeconds', 4), ...
        median(newSeconds), median(baselineSeconds), ratio, ternary(sc003Failed, 'FAIL', 'PASS'), ...
        blocks.reorient(1), blocks.reorient(2), blocks.reorient(2) / blocks.reorient(1), yesNo(blocks.reorientSame), ...
        blocks.components(1), blocks.components(2), blocks.components(2) / blocks.components(1), yesNo(blocks.componentsSame), ...
        blocks.nMoietyParts, blocks.moieties(1), blocks.moieties(2), blocks.moieties(2) / blocks.moieties(1), yesNo(blocks.moietiesSame));
    fclose(fid);
    fprintf('SC-003 ratio %.3f (%s)\n', ratio, ternary(sc003Failed, 'FAIL', 'PASS'));
end

if ~isIdentical
    error('conservedMoietyHotspotsCheck:mismatch', ...
        'n1960 outputs differ from the golden run; see %s.', resultsPath);
end
if sc003Failed
    error('conservedMoietyHotspotsCheck:sc003', ...
        'SC-003 failed: the median ratio is above 0.65; see %s.', resultsPath);
end

%% Local functions
function blocks = benchmarkBlocks(inputsFile)
% Old block code against the new code on the real n1960 ATG (research R1, probeHotspots.m)
S = load(inputsFile, 'ATG', 'BIG');
ATG0 = S.ATG;
BIG = S.BIG;
clear S

% reorientation: the pre-change loop against the one-pass swap now in the source
orientationATG2dATM = ATG0.Edges.orientationATG2dATM;
ATGa = ATG0;
tStart = tic;
for i = 1:numedges(ATGa)
    if orientationATG2dATM(i) == -1
        ATGa.Edges.HeadAtomIndex(i) = ATGa.Edges.EndNodes(i, 2);
        ATGa.Edges.TailAtomIndex(i) = ATGa.Edges.EndNodes(i, 1);
        HeadAtom = ATGa.Edges.TailAtom{i};
        TailAtom = ATGa.Edges.HeadAtom{i};
        ATGa.Edges.HeadAtom{i} = HeadAtom;
        ATGa.Edges.TailAtom{i} = TailAtom;
        ATGa.Edges.Trans{i} = [HeadAtom '#' TailAtom];
    end
end
oldReorient = toc(tStart);
ATGb = ATG0;
tStart = tic;
reorientedBool = orientationATG2dATM == -1;
edgesATG = ATGb.Edges;
newHeadAtom = edgesATG.TailAtom(reorientedBool);
newTailAtom = edgesATG.HeadAtom(reorientedBool);
headAtomIndex = edgesATG.HeadAtomIndex;
headAtomIndex(reorientedBool) = edgesATG.EndNodes(reorientedBool, 2);
tailAtomIndex = edgesATG.TailAtomIndex;
tailAtomIndex(reorientedBool) = edgesATG.EndNodes(reorientedBool, 1);
headAtoms = edgesATG.HeadAtom;
headAtoms(reorientedBool) = newHeadAtom;
tailAtoms = edgesATG.TailAtom;
tailAtoms(reorientedBool) = newTailAtom;
transNames = edgesATG.Trans;
transNames(reorientedBool) = cellfun(@(headAtom, tailAtom) [headAtom '#' tailAtom], ...
    newHeadAtom, newTailAtom, 'UniformOutput', false);
ATGb.Edges.HeadAtomIndex = headAtomIndex;
ATGb.Edges.TailAtomIndex = tailAtomIndex;
ATGb.Edges.HeadAtom = headAtoms;
ATGb.Edges.TailAtom = tailAtoms;
ATGb.Edges.Trans = transNames;
newReorient = toc(tStart);
blocks.reorient = [oldReorient, newReorient];
blocks.reorientSame = isequaln(ATGa.Edges, ATGb.Edges) && isequaln(ATGa.Nodes, ATGb.Nodes);
clear ATGa ATGb

% component subgraphs: the pre-change loop against extractPartitionSubgraphs
atoms2component = conncomp(ATG0)';
nComps = max(atoms2component);
tStart = tic;
oldParts = cell(nComps, 1);
for i = 1:nComps
    oldParts{i, 1} = subgraph(ATG0, atoms2component == i);
end
oldComponents = toc(tStart);
tStart = tic;
newParts = extractPartitionSubgraphs(ATG0, atoms2component);
newComponents = toc(tStart);
blocks.components = [oldComponents, newComponents];
blocks.componentsSame = numel(oldParts) == numel(newParts) && all(cellfun(@(a, b) ...
    isequaln(a.Nodes, b.Nodes) && isequaln(a.Edges, b.Edges), oldParts, newParts));
clear oldParts newParts

% moiety graphs, on a stand-in partition (moiety = component; the real moiety indices only
% exist later in the run)
bondEnds = BIG.Edges.EndNodes;
moietyBondIndex = zeros(size(bondEnds, 1), 1);
inside = atoms2component(bondEnds(:, 1)) == atoms2component(bondEnds(:, 2));
moietyBondIndex(inside) = atoms2component(bondEnds(inside, 1));
nodeTable = ATG0.Nodes;
nodeTable.MoietyIndex = atoms2component;
ABG = graph(addvars(BIG.Edges, moietyBondIndex, 'NewVariableNames', 'MoietyBondIndex'), nodeTable);
uniqueMoietyIndices = unique(ABG.Nodes.MoietyIndex);
tStart = tic;
oldMG = cell(numel(uniqueMoietyIndices), 1);
for i = 1:numel(uniqueMoietyIndices)
    currentMoietyIndex = uniqueMoietyIndices(i);
    nodeIndices = find(ABG.Nodes.MoietyIndex == currentMoietyIndex);
    subgraphNodes = subgraph(ABG, nodeIndices);
    edgeIndices = find(subgraphNodes.Edges.MoietyBondIndex == currentMoietyIndex);
    oldMG{i, 1} = graph(subgraphNodes.Edges(edgeIndices, :), subgraphNodes.Nodes);
end
oldMoieties = toc(tStart);
tStart = tic;
moietyOfNode = ABG.Nodes.MoietyIndex;
[bondSource, bondTarget] = findedge(ABG);
moietyBondIndexABG = ABG.Edges.MoietyBondIndex;
isInternalBond = moietyBondIndexABG == moietyOfNode(bondSource) & ...
    moietyBondIndexABG == moietyOfNode(bondTarget);
newMG = extractPartitionSubgraphs(ABG, moietyOfNode, isInternalBond);
newMoieties = toc(tStart);
blocks.moieties = [oldMoieties, newMoieties];
blocks.nMoietyParts = numel(uniqueMoietyIndices);
blocks.moietiesSame = numel(oldMG) == numel(newMG) && all(cellfun(@(a, b) ...
    isequaln(a.Nodes, b.Nodes) && isequaln(a.Edges, b.Edges), oldMG, newMG));
end

function s = yesNo(tf)
s = ternary(tf, 'yes', 'NO');
end

function out = ternary(condition, a, b)
if condition
    out = a;
else
    out = b;
end
end
