function FileString = generateFieldDescriptionFile(FileName)
%generateFieldDescriptionFile generateGenerates the ModelFields.md file
%describing the Required and Optional Fields of a COBRA model.
%
% USAGE generateFieldDescriptionFile(FileName)
%
% OPTIONAL INPUT
%
% FileName:     The FileName to write to. (default [CBTDIR filesep 'docs' filesep 'source' filesep 'Fields' filesep 'COBRAModelFields.md'])
%
%
% 
global CBTDIR
if ~exist('FileName','var')
    if isempty(CBTDIR)
        initCobraToolbox
    end
    FileName = [CBTDIR filesep 'docs' filesep 'source' filesep 'Fields' filesep 'COBRAModelFields.md'];
end

[requiredFields,optionalFields] = getDefinedFieldProperties();


FileString = sprintf('# Fields in the model structure\n\n');
FileString = strjoin({FileString, sprintf(['Contents:\n',...
                                        '1. [Required Fields](#required-fields)\n',...
                                        '2. [Optional Fields](#optional-fields)',...
                    '3. [Field Support](#field-support)\n',...
					'4. [Model Specific Fields](#model-specific-fields)\n',...
					'5. [Annotation Definitions](#annotation-definitions)\n',...
					'\n',...
					'### Required Fields: \n',...
					'Required fields are necessary to make a model be compliant with the COBRA Toolbox. Missing a required field can lead to errors when using COBRA Toolbox Functions. Verification is an evaluateable statement that the field must conform to.\n',...
					'\n',...
					'| Field Name | Field Type | Field Description | Verification | \n',...
					'|---|---|---|---|\n'])},'');

for i=1:size(requiredFields,1)
	string = sprintf('|`%s`| %s | %s | `%s` | \n',requiredFields{i,1},requiredFields{i,5},requiredFields{i,6},requiredFields{i,4});		
	FileString = strjoin({FileString,string},'');
end		
FileString = strjoin({FileString,sprintf(['### Optional Fields\n',...
				'Optional Fields are fields which are required by some functions (if not present, the function will report a corresponding message).\n',...
				'\n',...
				'| `Field Name` | Field Type | Field Description | Verification | \n',...
				'|---|---|---|---|\n'])},'');
for i=1:size(optionalFields,1)
	string = sprintf('|`%s`| %s | %s | `%s` | \n',optionalFields{i,1},optionalFields{i,5},optionalFields{i,6},optionalFields{i,4});		
	FileString = strjoin({FileString,string},'');
end
FileString = strjoin({FileString,sprintf(['### Model Specific Fields\n',...
					'Some models might contain additional model specific fields that are not defined COBRA model fields. These fields will commonly not be considered by COBRA toolbox methods, and using toolbox methods can render these fields inconsistent (e.g. if the number of reactions changes, a model specific field linked to reactions might have the wrong number of entries or the values might no longer correspond to the correct indices). \n',...
					'\n',...
					'### Field Support\n',...
					'All optional and all required fields are supported by all COBRA Toolbox functions. Using COBRA Toolbox Functions will not make a model inconsistent, but manual modifications of fields might lead to an inconsistent model.\n',...
					'Use verifyModel(model) to determine, if the model is a valid COBRA Toolbox model.\n',...
					'\n',...
					'### Additional fields (future development)\n',...
					'Fields starting with met, rxn, comp or gene that are not defined above, will be assumed to be annotation fields, and IO methods will try to map them to identifiers.org registered databases.'])},'');
fileID = fopen(FileName,'w');
fprintf(fileID,FileString);
fclose(fileID);
