function draftModelIDs=printRefinedModelIDs(draftFolder)
% This function prints the adapted names of the draft reconstruction
% entered into DEMETER. The adapted names need to be present in the
% MicrobeID column of the file with taxonomic information exactly as
% written in the output refinedModelIDs.
%
% USAGE: refinedModelIDs = printRefinedModelIDs(draftFolder)
%
% INPUT
% draftFolder            Folder with draft COBRA models generated by
%                        KBase pipeline to analyze
%
% OUTPUT
% refinedModelIDs        Names of the refined models generated by DEMETER
%
% AUTHOR: Almut Heinken, 01/2021.

% Get all models from the input folder
dInfo = dir(fullfile(draftFolder, '**/*.*'));
dInfo = dInfo(~[dInfo.isdir]);
models={dInfo.name};
models=models';
% remove any files that are not SBML or mat files
delInd=find(~any(contains(models(:,1),{'sbml','mat'})));
models(delInd,:)=[];
for i=1:length(models)
    draftModelIDs{i,1}=adaptDraftModelID(models{i});
end

end
