Description of getFormulaFromInChI
getFormulaFromInChI
PURPOSE
extract formula from InChI
SYNOPSIS
function formula=getFormulaFromInChI(InChI)
DESCRIPTION
 extract formula from InChI
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
modelMetabolitesToSDF write out an SDF which is effectively a set of mol files concatenated
getChargeFromInChI return the charge from a given InChI string
setupThermoModel Thermodynamically constrains a COBRA model.
SOURCE CODE
function formula=getFormulaFromInChI(InChI)
% extract formula from InChI
[token,rem] = strtok(InChI, '/');
formula=strtok(rem, '/');