function bioQualifiers = getBioQualifiers()
% Get a list of possible bioqualifiers
% USAGE:
%    annotationQualifiers = getBioQualifiers()
%
% OUTPUT:
%    bioQualifiers:    A cell array of bioquaifier strings.


bioQualifiers = {'encodes', 'encodement',...
        'hasPart', 'part',...
        'hasProperty', 'property',...
        'hasVersion', 'version',...
        'is', 'identity',...
        'isDescribedBy', 'description',...
        'isEncodedBy', 'encoder',...
        'isHomologTo', 'homolog',...
        'isPartOf', 'parthood',...
        'isPropertyOf', 'propertyBearer',...
        'isVersionOf', 'hypernym',...
        'occursIn', 'container',...
        'hasTaxon', 'taxon',...
        'isRelatedTo', 'relation'};