function bioQualifiers = getBioQualifiers()
% Get a list of possible bioqualifiers
%
% USAGE:
%    annotationQualifiers = getBioQualifiers()
%
% OUTPUT:
%    bioQualifiers:    A cell array of bioqualifier strings in descending order.


bioQualifiers = {'version','taxon','relation',...
                 'propertyBearer','property',...
                 'parthood','part','origin','occursIn',...
                 'isVersionOf','isRelatedTo','isPropertyOf',...
                 'isPartOf','isInstanceOf','isHomologTo','isEncodedBy',...
                 'isDescribedBy','isDerivedFrom','is','instance','identity',...
                 'hypernym','homolog','hasVersion',...
                 'hasTaxon','hasProperty','hasPart','hasInstance',...
                 'encodes','encoder','encodement',...
                 'description','container','class'};