function [requiredFields,optionalFields] = getDefinedFieldProperties()
%GETDEFINEDFIELDPROPERTIES returns the Fields defined in the COBRA Toolbox
%along with checks for their properties 
%
% The returned Cell arrays are structured as follows:
% X{:,1} are the field names
% X{:,2} are the associated fields for the first dimension (i.e.
%        size(model.(X{A,1}),1) == size(model.(X{A,2}),1) has to evaluate
%        to true
% X{:,3} are the associated fields for the second dimension (i.e.
%        size(model.(X{A,1}),2) == size(model.(X{A,2}),1) has to evaluate
%        to true
% X{:,4} are evaluateable statements, which have to evaluate to true for
%        the model to be valid, these mainly check the content types.
%        E.g. 
%               x = model.(X{A,1});
%               eval(X{A,4}) has to return 1
%OUTPUTS
% requiredFields        The fields a model must have in order to be a valid
%                       COBRA Toolbox model
% optionalFields        The Fields which are supported by the COBRA
%                       Toolbox.
%
requiredFields = ...
    {'S','mets','rxns','isnumeric(x) || issparse(x)';...
    'b','mets',1,'isnumeric(x)';...
    'csense','mets',1,'ischar(x)';...
    'lb','rxns',1,'isnumeric(x)';...
    'ub','rxns',1,'isnumeric(x)';...
    'c','rxns',1,'isnumeric(x)';...
    'osense',1,1,'isnumeric(x)';...
    'rxns','rxns',1,'iscell(x) && ~any(cellfun(@isempty, x)) && all(cellfun(@(y) ischar(y) , x))';...
    'mets','mets',1,'iscell(x) && ~any(cellfun(@isempty, x)) && all(cellfun(@(y) ischar(y) , x))';...
    'genes','genes',1,'iscell(x) && ~any(cellfun(@isempty, x)) && all(cellfun(@(y) ischar(y) , x))';...
    'rules','rxns',1,'iscell(x) && all(cellfun(@(y) ischar(y) , x))'};



optionalFields = ...
    {'metCharges','mets',1,'isnumeric(x)';...
    'metFormulas','mets',1,'iscell(x) && all(cellfun(@(y) ischar(y) , x))';...
    'metSMILES','mets',1,'iscell(x) && all(cellfun(@(y) ischar(y) , x))';...
    'metNames','mets',1,'iscell(x) && all(cellfun(@(y) ischar(y) , x))';...
    'metNotes','mets',1,'iscell(x) && all(cellfun(@(y) ischar(y) , x))';...
    'description',NaN,NaN,'ischar(x) || isstruct(x)' ;...
    'modelVersion',NaN,NaN,'isstruct(x)';...
    'ConfidenceScores','rxns',1,'isnumeric(x)';...
    'gRRules','rxns',1,'iscell(x) && all(cellfun(@(y) ischar(y) , x))';...
    'rxnGeneMat','rxns','genes','issparse(x) || isnumeric(x) || islogical(x)';...
    'rxnNames','rxns',1,'iscell(x) && all(cellfun(@(y) ischar(y) , x))';...
    'rxnNotes','rxns',1,'iscell(x) && all(cellfun(@(y) ischar(y) , x))';...
    'subSystems','rxns',1,'iscell(x) && all(cellfun(@(y) ischar(y) , x))';...
    'geneSubSystems','genes',1,'iscell(x) && all(cellfun(@(y) ischar(y) , x))';...
    'compNames','comp',1,'iscell(x) && all(cellfun(@(y) ischar(y) , x))';...    
    'comp',NaN,1,'iscell(x) && all(cellfun(@(y) ischar(y) , x))';...
    'annotations',NaN,NaN,'isstruct(x)'};