Description of changeObjective
changeObjective
PURPOSE
changeObjective Changes the objective function of a constraint-based model
SYNOPSIS
function model = changeObjective(model,rxnNameList,objectiveCoeff)
DESCRIPTION
changeObjective Changes the objective function of a constraint-based model
 model = changeObjective(model,rxnNameList,objectiveCoeff)
INPUTS
 model             COBRA structure
 rxnNameList       List of reactions (cell array or string)
OPTIONAL INPUT
 objectiveCoeff    Value of objective coefficient for each reaction
                   (Default = 1)
OUTPUT
 model             COBRA model structure with new objective
 Monica Mo & Markus Herrgard - 8/21/06
CROSS-REFERENCE INFORMATION
This function calls:
findRxnIDs findRxnIDs Find reaction numbers in a model
This function is called by:
analyzeGCdesign analyzeGCdesign Analyze results with replacement knockouts
analyzeOptKnock analyzeOptKnock determines whether an optknock solution is growth coupled
doubleProductionEnvelope doubleProductionEnvelope plots maximum growth rate as a function of the
multiProductionEnvelope multiProductionEnvelope Calculates the byproduct secretion envelopes for
multiProductionEnvelopeInorg multiProductionEnvelopeInorg calculates the byproduct secretion envelopes
simpleOptKnock simpleOptKnock Simple OptKnock to check all one gene or reaction deletions for
testOptKnockSol testOptKnockSol Test an OptKnock knockout strain
doubleRobustnessAnalysis doubleRobustnessAnalysis Performs robustness analysis for a pair of reactions of
pFBA Parsimoneous enzyme usage Flux Balance Analysis - method that optimizes
productionEnvelope productionEnvelope Calculates the byproduct secretion envelope
reduceModel reduceModel Removes from the model all of the reactions that are never used (max and
robustnessAnalysis robustnessAnalysis Performs robustness analysis for a reaction of
testPathway this gapfiling function allows the user to see if given one metabolite A,
SOURCE CODE
function model = changeObjective(model,rxnNameList,objectiveCoeff)
%changeObjective Changes the objective function of a constraint-based model
%
% model = changeObjective(model,rxnNameList,objectiveCoeff)
%
%INPUTS
% model             COBRA structure
% rxnNameList       List of reactions (cell array or string)
%
%OPTIONAL INPUT
% objectiveCoeff    Value of objective coefficient for each reaction
%                   (Default = 1)
%
%OUTPUT
% model             COBRA model structure with new objective
%
% Monica Mo & Markus Herrgard - 8/21/06
if (nargin < 3)
    objectiveCoeff = 1;
end
rxnID = findRxnIDs(model,rxnNameList);
model.c = zeros(size(model.c));
if iscell(rxnNameList)
    missingRxns = rxnNameList(rxnID == 0);
    for i = 1:length(missingRxns)
        fprintf('%s not in model\n',missingRxns{i});
    end
    rxnID = rxnID(rxnID ~= 0);
    if (length(objectiveCoeff) > 1)
        objectiveCoeff = objectiveCoeff(rxnID ~= 0);
    end
end
if (isempty(rxnID) | rxnID == 0)
    error('Objective reactions not found in model!');
else
    model.c(rxnID) = objectiveCoeff;
end