Description of findGenesFromRxns
findGenesFromRxns
PURPOSE
findGenesFromRxns make a gene list of the genes that correspond to the
SYNOPSIS
function [geneList]=findGenesFromRxns(model,reactions)
DESCRIPTION
findGenesFromRxns make a gene list of the genes that correspond to the
selected reactions
 [geneList]=findGenesFromRxns(model,reactions)
INPUTS
 model         COBRA model structure
 reactions     Reactions to find the corresponding genes for
OUTPUT
 geneList      List of genes corresponding to reactions
 Markus Herrgard (7/3/06)
CROSS-REFERENCE INFORMATION
This function calls:
findRxnIDs findRxnIDs Find reaction numbers in a model
columnVector columnVector Converts a vector to a column vector
This function is called by:
pFBA Parsimoneous enzyme usage Flux Balance Analysis - method that optimizes
SOURCE CODE
function [geneList]=findGenesFromRxns(model,reactions)
%findGenesFromRxns make a gene list of the genes that correspond to the
%selected reactions
%
% [geneList]=findGenesFromRxns(model,reactions)
%
%INPUTS
% model         COBRA model structure
% reactions     Reactions to find the corresponding genes for
%
%OUTPUT
% geneList      List of genes corresponding to reactions
% Markus Herrgard (7/3/06)
rxnInd = findRxnIDs(model, reactions);
RxnNotInModel = find(rxnInd==0);
if ~isempty(RxnNotInModel)
    for i = 1:length(RxnNotInModel)
        display(cat(2,'The reaction "', reactions{RxnNotInModel(i)},'" is not in your model!'));
    end
end
rxnInd(RxnNotInModel) = [];
reactions(RxnNotInModel) = [];
for i = 1:length(rxnInd)
    geneList{i} = model.genes(find(model.rxnGeneMat(rxnInd(i),:)));
end
geneList = columnVector(geneList);