Description of findExcRxns
findExcRxns
PURPOSE
findExcRxns Find exchange and uptake rxns
SYNOPSIS
function [selExc,selUpt] = findExcRxns(model,inclObjFlag,irrevFlag)
DESCRIPTION
findExcRxns Find exchange and uptake rxns
 [selExc,selUpt] = findExcRxns(model,inclObjFlag,irrevFlag)
INPUT
 model             COBRA model structure
OPTIONAL INPUTS
 inclObjFlag       Include objective rxns in the exchange rxn set (1) or not (0)
                   (Default = false)
 irrevFlag         Model is in irreversible format (1) or not
                   (Default = false)
OUTPUTS
 selExc            Boolean vector indicating whether each reaction in
                   model is exchange or not
 selUpt            Boolean vector indicating whether each reaction in
                   model is nutrient uptake or not
 Exchange reactions only have one non-zero (+1/-1) element in the
 corresponding column of the stoichiometric matrix. Uptake reactions are
 exchange reactions are exchange reactions with negative lower bounds.
 10/14/05 Markus Herrgard
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
GDLS GDLS (Genetic Design through Local Search) attempts to find genetic
multiProductionEnvelope multiProductionEnvelope Calculates the byproduct secretion envelopes for
multiProductionEnvelopeInorg multiProductionEnvelopeInorg calculates the byproduct secretion envelopes
randomKO randomKO knock out N random genes and reports products from FBA
theoretMaxProd determines the max theoretical output for each exchange reaction
dynamicFBA dynamicFBA Perform dynamic FBA simulation using the static optimization
findOrphanRxns findOrphanRxns find all orphan reactions in model (reactions with no
pFBA Parsimoneous enzyme usage Flux Balance Analysis - method that optimizes
printFluxVector printFluxVector Print a flux vector with reaction labels
printUptakeBound printUptakeBound Print substrate uptake bounds
dynamicRFBA dynamicRFBA - perform dynamic rFBA simulation using the static optimization
solveBooleanRegModel solveBooleanRegModel - determines the next state of the regulatory
reporterMets reporterMets Implements the reporter metabolites algorithm by Patil &
SOURCE CODE
function [selExc,selUpt] = findExcRxns(model,inclObjFlag,irrevFlag)
%findExcRxns Find exchange and uptake rxns
%
% [selExc,selUpt] = findExcRxns(model,inclObjFlag,irrevFlag)
%
%INPUT
% model             COBRA model structure
%
%OPTIONAL INPUTS
% inclObjFlag       Include objective rxns in the exchange rxn set (1) or not (0)
%                   (Default = false)
% irrevFlag         Model is in irreversible format (1) or not
%                   (Default = false)
%
%OUTPUTS
% selExc            Boolean vector indicating whether each reaction in
%                   model is exchange or not
% selUpt            Boolean vector indicating whether each reaction in
%                   model is nutrient uptake or not
%
% Exchange reactions only have one non-zero (+1/-1) element in the
% corresponding column of the stoichiometric matrix. Uptake reactions are
% exchange reactions are exchange reactions with negative lower bounds.
%
% 10/14/05 Markus Herrgard
if (nargin < 2)
    inclObjFlag = false;
end
if (nargin < 3)
    irrevFlag = false;
end
if (~irrevFlag)
    % Find exchange rxns
    selExc = full((sum(model.S==-1,1) ==1) & (sum(model.S~=0) == 1))' | full((sum(model.S==1,1) ==1) & (sum(model.S~=0) == 1))';
    if (isfield(model,'c'))
        % Remove obj rxns
        if (~inclObjFlag)
            selExc(model.c ~= 0) = false;
        else
            selExc(model.c ~= 0) = true;
        end
    end
    if (isfield(model,'lb'))
        % Find uptake rxns
        selUpt = full(model.lb < 0 & selExc);
    else
        selUpt = [];
    end
else
    % Find exchange rxns
    selExc = full((sum(abs(model.S)==1,1) ==1) & (sum(model.S~=0) == 1))';
    if (isfield(model,'c'))
    % Remove obj rxns
    if (~inclObjFlag)
        selExc(model.c ~= 0) = false;
    else
        selExc(model.c ~= 0) = true;
    end
    end
    % Find uptake rxns
    selUpt = full((sum(model.S==1,1) ==1) & (sum(model.S~=0) == 1))';
end