Description of findRxnIDs
findRxnIDs
PURPOSE
findRxnIDs Find reaction numbers in a model
SYNOPSIS
function rxnID = findRxnIDs(model,rxnList)
DESCRIPTION
findRxnIDs Find reaction numbers in a model
 rxnID = findRxnIDs(model,rxnList)
INPUTS
 model     COBRA model strcture
 rxnList   List of reactions
OUTPUT
 rxnID     IDs for reactions corresponding to rxnList
 Markus Herrgard 4/21/06
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
changeObjective changeObjective Changes the objective function of a constraint-based model
changeRxnBounds changeRxnBounds Change upper or lower bounds of a reaction or a set of
changeRxnMets changeRxnMets Change metabolites in a specified reaction, or
checkCobraModelUnique checkCobraModelUnique Check uniqueness of reaction and metabolite names
deleteModelGenes deleteModelGenes Delete one or more genes and constrain the reactions
augmentBOF augmentObjectiveFunction adjusts the objective function to eliminate
multiProductionEnvelope multiProductionEnvelope Calculates the byproduct secretion envelopes for
optGeneFitness optGeneFitness GeneOptFitness the fitness function
theoretMaxProd determines the max theoretical output for each exchange reaction
doubleRobustnessAnalysis doubleRobustnessAnalysis Performs robustness analysis for a pair of reactions of
findGenesFromRxns findGenesFromRxns make a gene list of the genes that correspond to the
findMetabolicJunctions findMetabolicJunctions Find metabolic branchpoints with different numbers
findNeighborRxns findNeighborRxns Identifies the reactions and the corresponding genes
C13ConfidenceInterval v0 - set of flux vectors to be used as initial guesses. They may be
readBooleanRegModel readBooleanRegModel Read Boolean regulatory network model
keepCompartment This function removes reactions in all compartments except those
phenotypePhasePlane phenotypePhasePlane Plots three phenotype phase planes for two reactions. The first plot is
printRxnFormula printRxnFormula Print the reaction formulas for a list of reactions
solveBooleanRegModel solveBooleanRegModel - determines the next state of the regulatory
createTissueSpecificModel createTissueSpecificModel Create draft tissue specific model from mRNA expression data
robustnessAnalysis robustnessAnalysis Performs robustness analysis for a reaction of
compareSampleTraj compareSampleHist Compare flux histogramns for two or more samples
plotSampleHist plotSampleHist Compare flux histograms for one or more samples
SOURCE CODE
function rxnID = findRxnIDs(model,rxnList)
%findRxnIDs Find reaction numbers in a model
%
% rxnID = findRxnIDs(model,rxnList)
%
%INPUTS
% model     COBRA model strcture
% rxnList   List of reactions
%
%OUTPUT
% rxnID     IDs for reactions corresponding to rxnList
%
% Markus Herrgard 4/21/06
if (iscell(rxnList))
    [tmp,rxnID] = ismember(rxnList,model.rxns);
else
    rxnID = find(strcmp(model.rxns,rxnList));
    if (isempty(rxnID))
        rxnID = 0;
    end
    if (length(rxnID) > 1)
        rxnID = rxnID(1);
    end
end