function cleanFilesFastFVA(dirLogFiles, userInteraction)
% Clean log and result files generated by fastFVA
%
% USAGE:
%    cleanFiles(dirLogFiles, userInteraction)
%
% INPUT:
%    dirLogFiles:       Directory where the log files of fastFVA are located
%    userInteraction:   Boolean variable for requesting explicitly if the files should be removed
%
% .. Author: Laurent Heirendt, LCSB
%

global CBTDIR

if nargin < 2
    userInteraction = true;
end

% save the current directory
currentDir = pwd;

% clear previous log files in logFiles/
D = dir([dirLogFiles filesep '*.log']);
nbFiles = numel(D);
if nbFiles > 0
    fprintf('\n Number of files in fastFVALogFiles/: %d\n', nbFiles);

    if userInteraction
        m = input('\n Do you want to clean all log files in fastFVALogFiles/ ? - Y/N [Y]: ','s');
    end

    if strcmpi(m, 'y') || ~userInteraction
        cd(dirLogFiles);
        delete *.log
        fprintf(' >> All log files in fastFVALogFiles/ removed.\n');
    end
else
    fprintf('\n The directory fastFVALogFiles/ is empty.\n');
end

% change back to the current directory
cd(currentDir);

fprintf('\n');
