Description of realpH
realpH
PURPOSE
Apparent glass electrode pH is not the same as real pH for thermodynamic calculations.
SYNOPSIS
function [pHr,pHAdjustment]=realpH(pHa,temp,is)
DESCRIPTION
 Apparent glass electrode pH is not the same as real pH for thermodynamic calculations.
 Given the experimental glass electrode measurement of pH, this function returns
 the pH to be used for thermodynamic calculations, pHc = -log10[H+],
 by subtracting the effect of the ion atmosphere around H+ which
 reduces its activity coefficient below unity.
 See p49 Alberty 2003
INPUT
 pHa       apparent pH, measured by glass electrode experimentally
 temp      experimentally measured temperature
 is        estimate of ionic strength
OUTPUT
 pHr           real pH to be used for thermodynamic calculations
 pHAdjustment  adjustment to pH
 Ronan M.T. Fleming
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
moleFraction mole fraction of different metabolite species that make up a reactant
plotMoleFraction Plot the mole fractions of metabolite species of a reactant as a function of pH, ionic strength, charge and temperature.
scanThermoParam parameter scan of the thermodynamic parameters for each metabolite
setupThermoModel Thermodynamically constrains a COBRA model.
SOURCE CODE
function [pHr,pHAdjustment]=realpH(pHa,temp,is)
% Apparent glass electrode pH is not the same as real pH for thermodynamic calculations.
%
% Given the experimental glass electrode measurement of pH, this function returns
% the pH to be used for thermodynamic calculations, pHc = -log10[H+],
% by subtracting the effect of the ion atmosphere around H+ which
% reduces its activity coefficient below unity.
% See p49 Alberty 2003
%
%INPUT
% pHa       apparent pH, measured by glass electrode experimentally
% temp      experimentally measured temperature
% is        estimate of ionic strength
%
%OUTPUT
% pHr           real pH to be used for thermodynamic calculations
% pHAdjustment  adjustment to pH
%
% Ronan M.T. Fleming
%p48 Alberty
gibbscoeff = 1.10708 - (1.54508*temp)/10^3 + (5.95584*temp^2)/10^6;
%Adjust pH using Extended Debye-Huckle equation
pHAdjustment = ((gibbscoeff*(is^(0.5))) / (log(10)*(1+1.6*(is^(0.5)))));
% fprintf('%s\t%f\n','pH adjustment',phAdjustment);
pHr = pHa - pHAdjustment;