function gurobiParam = setGurobiParam(param)
% Converts a COBRA-style solver parameter structure into a Gurobi-compatible
% parameter structure, translating COBRA parameter names to their Gurobi
% equivalents and filtering to only the fields Gurobi recognises
%
% The param struct contains Gurobi parameters. A full list may be
% found on the Parameter page of the reference manual:
% https://www.gurobi.com/documentation/current/refman/parameter_descriptions.html
% Parameters must be in TimeLimit not timelimit or timeLimit format, see
% below for full list that are eligible to be passed to the solver.
%
% USAGE:
%
%    gurobiParam = setGurobiParam(param)
%
% INPUT:
%    param:             Structure with COBRA-style and/or Gurobi-style
%                       solver parameters, with fields (all optional):
%
%                         * .timelimit - alias for `.TimeLimit`, copied to
%                           `.TimeLimit` if `.TimeLimit` is absent
%                         * .TimeLimit - Gurobi time limit in seconds
%                         * .multiscale - if 1, disables Gurobi scaling by
%                           setting `.ScaleFlag` to 0
%                         * .ScaleFlag - Gurobi scaling flag, set to 0 when
%                           `.multiscale == 1`
%                         * .lifted - if 1, sets `.Aggregate` to 1 and
%                           `.Presolve` to 0 (suitable for a lifted/ill-scaled
%                           model)
%                         * .Aggregate - Gurobi presolve aggregation level,
%                           set to 1 when `.lifted == 1`
%                         * .Presolve - Gurobi presolve level (-1 automatic,
%                           0 off, 1 conservative, 2 aggressive), set to 0
%                           when `.lifted == 1`
%                         * .method - backward-compatible algorithm selector;
%                           if present and non-empty, its value is copied to
%                           `.([lower(problemType) 'method'])` unless that
%                           field already exists
%                         * .problemType - COBRA problem type string (e.g.
%                           `'LP'`, `'QP'`), combined with `.method` to build
%                           the `lpmethod`/`qpmethod` field name
%                         * .lpmethod - COBRA-style LP algorithm name
%                           (`'AUTOMATIC'`, `'PRIMAL'`, `'DUAL'`,
%                           `'BARRIER'`, `'CONCURRENT'`,
%                           `'DETERMINISTIC_CONCURRENT'`), translated to the
%                           numeric Gurobi `.Method`
%                         * .qpmethod - COBRA-style QP algorithm name
%                           (`'AUTOMATIC'`, `'PRIMAL'`, `'DUAL'`,
%                           `'BARRIER'`), translated to the numeric Gurobi
%                           `.Method`
%                         * .Method - Gurobi algorithm used to solve
%                           continuous models (-1 automatic, 0 primal
%                           simplex, 1 dual simplex, 2 barrier, 3
%                           concurrent, 4 deterministic concurrent)
%                         * .printLevel - COBRA print level, used to set
%                           `.OutputFlag` and `.DisplayInterval` when they
%                           are not already present (both are set silent in
%                           the current implementation, regardless of level)
%                         * .OutputFlag - Gurobi console output flag
%                         * .DisplayInterval - Gurobi console display
%                           interval in seconds
%                         * .FeasibilityTol - Gurobi primal feasibility
%                           tolerance, set from `.feasTol` if not already
%                           present
%                         * .feasTol - COBRA-style primal feasibility
%                           tolerance, source value for `.FeasibilityTol`
%                         * .OptimalityTol - Gurobi dual feasibility
%                           tolerance, set from `.optTol` if not already
%                           present
%                         * .optTol - COBRA-style dual feasibility
%                           tolerance, source value for `.OptimalityTol`
%
% OUTPUT:
%    gurobiParam:       Structure containing only the fields recognised by
%                       the Gurobi `gurobi.m` interface (the permitted
%                       parameter list), translated from the COBRA-style
%                       names in `param`

if isfield(param,'timelimit')
    param.TimeLimit=param.timelimit;
end

if isfield(param,'multiscale') && param.multiscale==1
    param.ScaleFlag=0;
end

if isfield(param,'lifted') && param.lifted==1
    param.Aggregate=1;
    % Presolve
    % Controls the presolve level
    % Type:	int
    % Default value:	-1
    % Minimum value:	-1
    % Maximum value:	2
    % Controls the presolve level. A value of -1 corresponds to an automatic setting.
    % Other options are off (0), conservative (1), or aggressive (2). More aggressive application
    % of presolve takes more time, but can sometimes lead to a significantly tighter model.
    param.Presolve=0;
end

%backward compatibility
if isfield(param,'method')
    if isempty(param.method)
        param = rmfield(param,'method');
    else
        if ~isfield(param,[lower(param.problemType) 'method'])
            param.([lower(param.problemType) 'method'])=param.method;
        end
    end
end

% https://www.gurobi.com/documentation/current/refman/method.html
% params.method gives the method used to solve continuous models
% -1=automatic,
%  0=primal simplex,
%  1=dual simplex,
%  2=barrier,
%  3=concurrent,
%  4=deterministic concurrent
% i.e. params.method     = 1;          % use dual simplex method
if isfield(param,'lpmethod')
    %gurobiAlgorithms = {'AUTOMATIC','PRIMAL','DUAL','BARRIER','CONCURRENT','CONCURRENT_DETERMINISTIC'};
    % -1=automatic,
    % 0=primal simplex,
    % 1=dual simplex,
    % 2=barrier,
    % 3=concurrent,
    % 4=deterministic concurrent
    switch param.lpmethod
        case 'AUTOMATIC'
            param.Method = -1;
        case 'PRIMAL'
            param.Method = 0;
        case 'DUAL'
            param.Method = 1;
        case 'BARRIER'
            param.Method = 2;
        case 'CONCURRENT'
            param.Method = 3;
        case 'DETERMINISTIC_CONCURRENT'
            param.Method = 4;
        otherwise
            %https://www.gurobi.com/documentation/current/refman/method.html
            %Concurrent methods aren't available for QP and QCP.
            warning([param.lpmethod ' is an unrecognised param.qpmethod for gurobi'])
    end
    param = rmfield(param,'lpmethod');
end

% param.qpmethod gives the qpmethod used to solve continuous models
% -1=automatic,
%  0=primal simplex,
%  1=dual simplex,
%  2=barrier,
%  3=concurrent,
%  4=deterministic concurrent
% i.e. param.qpmethod     = 1;          % use dual simplex method
if isfield(param,'qpmethod')
    %gurobi QP algorithms = {'AUTOMATIC','PRIMAL','DUAL','BARRIER'};
    % -1=automatic,
    % 0=primal simplex,
    % 1=dual simplex,
    % 2=barrier,
    switch param.qpmethod
        case 'AUTOMATIC'
            param.Method = -1;
        case 'PRIMAL'
            param.Method = 0;
        case 'DUAL'
            param.Method = 1;
        case 'BARRIER'
            param.Method = 2;
        otherwise
            %https://www.gurobi.com/documentation/current/refman/method.html
            %Concurrent methods aren't available for QP and QCP.
            warning([param.qpmethod ' is an unrecognised param.qpmethod for gurobi'])
    end
    param = rmfield(param,'qpmethod');
end

if ~isfield(param,'OutputFlag')
    switch param.printLevel
        case 0
            param.OutputFlag = 0;
        case 1
            param.OutputFlag = 0;
        otherwise
            % silent
            param.OutputFlag = 0;
    end
end

if ~isfield(param,'DisplayInterval')
    switch param.printLevel
        case 0
            param.DisplayInterval = 1;
        case 1
            param.DisplayInterval = 1;
        otherwise
            % silent
            param.DisplayInterval = 1;
    end
end

if ~isfield(param,'FeasibilityTol')
    % Primal feasibility tolerance
    % Type:	double
    % Default value:	1e-6
    % Minimum value:	1e-9
    % Maximum value:	1e-2
    % All constraints must be satisfied to a tolerance of FeasibilityTol.
    % Tightening this tolerance can produce smaller constraint violations, but for
    % numerically challenging models it can sometimes lead to much larger iteration counts.
     param.FeasibilityTol = param.feasTol;
end
if ~isfield(param,'OptimalityTol')
    % Dual feasibility tolerance
    % Type:	double
    % Default value:	1e-6
    % Minimum value:	1e-9
    % Maximum value:	1e-2
    % Reduced costs must all be smaller than OptimalityTol in the improving direction in order for a model to be declared optimal.
     param.OptimalityTol = param.optTol;
end


% Permitted parameter fields
permittedFields = {...
'AggFill'...
'Aggregate'...
'BarConvTol'...
'BarCorrectors'...
'BarHomogeneous'...
'BarIterLimit'...
'BarOrder'...
'BarQCPConvTol'...
'BestBdStop'...
'BestObjStop'...
'BQPCuts'...
'BranchDir'...
'CliqueCuts'...
'CloudAccessID'...
'CloudHost'...
'CloudSecretKey'...
'CloudPool'...
'ComputeServer'...
'ConcurrentJobs'...
'ConcurrentMethod'...
'ConcurrentMIP'...
'ConcurrentSettings'...
'CoverCuts'...
'Crossover'...
'CrossoverBasis'...
'CSAPIAccessID'...
'CSAPISecret'...
'CSAppName'...
'CSAuthToken'...
'CSBatchMode'...
'CSClientLog'...
'CSGroup'...
'CSIdleTimeout'...
'CSManager'...
'CSPriority'...
'CSQueueTimeout'...
'CSRouter'...
'CSTLSInsecure'...
'CutAggPasses'...
'Cutoff'...
'CutPasses'...
'Cuts'...
'DegenMoves'...
'Disconnected'...
'DisplayInterval'...
'DistributedMIPJobs'...
'DualReductions'...
'FeasibilityTol'...
'FeasRelaxBigM'...
'FlowCoverCuts'...
'FlowPathCuts'...
'FuncPieceError'...
'FuncPieceLength'...
'FuncPieceRatio'...
'FuncPieces'...
'FuncMaxVal'...
'FuncNonlinear'...
'GomoryPasses'...
'GUBCoverCuts'...
'Heuristics'...
'IgnoreNames'...
'IISMethod'...
'ImpliedCuts'...
'ImproveStartGap'...
'ImproveStartNodes'...
'ImproveStartTime'...
'InfProofCuts'...
'InfUnbdInfo'...
'InputFile'...
'IntegralityFocus'...
'IntFeasTol'...
'IterationLimit'...
'JobID'...
'JSONSolDetail'...
'LazyConstraints'...
'LicenseID'...
'LiftProjectCuts'...
'LPWarmStart'...
'LogFile'...
'LogToConsole'...
'MarkowitzTol'...
'MemLimit'...
'Method'...
'MinRelNodes'...
'MIPFocus'...
'MIPGap'...
'MIPGapAbs'...
'MIPSepCuts'...
'MIQCPMethod'...
'MIRCuts'...
'MixingCuts'...
'ModKCuts'...
'MultiObjMethod'...
'MultiObjPre'...
'MultiObjSettings'...
'NetworkAlg'...
'NetworkCuts'...
'NLPHeur'...
'NodefileDir'...
'NodefileStart'...
'NodeLimit'...
'NodeMethod'...
'NonConvex'...
'NoRelHeurTime'...
'NoRelHeurWork'...
'NormAdjust'...
'NumericFocus'...
'OBBT'...
'ObjNumber'...
'ObjScale'...
'OptimalityTol'...
'OutputFlag'...
'PartitionPlace'...
'PerturbValue'...
'PoolGap'...
'PoolGapAbs'...
'PoolSearchMode'...
'PoolSolutions'...
'PreCrush'...
'PreDepRow'...
'PreDual'...
'PreMIQCPForm'...
'PrePasses'...
'PreQLinearize'...
'Presolve'...
'PreSOS1BigM'...
'PreSOS1Encoding'...
'PreSOS2BigM'...
'PreSOS2Encoding'...
'PreSparsify'...
'ProjImpliedCuts'...
'PSDCuts'...
'PSDTol'...
'PumpPasses'...
'QCPDual'...
'Quad'...
'Record'...
'ResultFile'...
'RINS'...
'RelaxLiftCuts'...
'RLTCuts'...
'ScaleFlag'...
'ScenarioNumber'...
'Seed'...
'ServerPassword'...
'ServerTimeout'...
'Sifting'...
'SiftMethod'...
'SimplexPricing'...
'SoftMemLimit'...
'SolutionLimit'...
'SolutionTarget'...
'SolFiles'...
'SolutionNumber'...
'StartNodeLimit'...
'StartNumber'...
'StrongCGCuts'...
'SubMIPCuts'...
'SubMIPNodes'...
'Symmetry'...
'Threads'...
'TimeLimit'...
'TokenServer'...
'TSPort'...
'TuneBaseSettings'...
'TuneCleanup'...
'TuneCriterion'...
'TuneDynamicJobs'...
'TuneJobs'...
'TuneMetric'...
'TuneOutput'...
'TuneResults'...
'TuneTargetMIPGap'...
'TuneTargetTime'...
'TuneTimeLimit'...
'TuneTrials'...
'TuneUseFilename'...
'UpdateMode'...
'UserName'...
'VarBranch'...
'WLSAccessID'...
'WLSSecret'...
'WLSToken'...
'WLSTokenDuration'...
'WLSTokenRefresh'...
'WorkerPassword'...
'WorkerPool'...
'WorkLimit'...
'ZeroHalfCuts'...
'ZeroObjNodes'};

fields = fieldnames(param);
fieldsToRemove = setdiff(fields, permittedFields);
%remove fields that should not be present
gurobiParam = rmfield(param, fieldsToRemove);

if isfield(gurobiParam,'logFile') && isempty(gurobiParam.logFile)
    gurobiParam = rmfield(gurobiParam,'logFile');
end
