function [map] = correctRxnNameCD(map, rxnStucture, rxnList)
% Correct the list of wrong reaction names in the map obtained from
% checkCDerrors given a list of reaction with the right names.
% Therefore, the wrong names in the map should become those of the model.
%
% USAGE:
%
%   [map] = correctRxnNameCD(map, rxnStucture, rxnList)
%
% INPUTS:
%    map:           A parsed model structure generated by
%                   'transformXML2Map' function
%    rxnStucture:   First OUTPUT obtained when running checkCDerrors
%    rxnList:       list of reactions with right names
%
% OUTPUT:
%    map:          corrected map
%
% .. Author: - J.modamio 18/07/2017. Belval, Luxembourg, 18/07/2017.

    rxn = rxnStucture;
    for i = 1:length(rxn.extraRxnsMap)
        index = find(ismember(map.rxnName, rxn.extraRxnsMap{i}));
        map.rxnName(index, 1) = rxnList(i);
    end

end
