function [map] = correctMetNameCD(map, metStructure, metList)
% Correct the list of wrong metabolites names in the map obtained from
% checkCDerrors given a list of metabolites with the right names.
% Therefore, the wrong names in the map should become those of the model.
%
% USAGE:
%
%   [map] = correctMetNameCD(map, metStructure, metList)
%
% INPUTS:
%    map:           A parsed model structure generated by
%                   'transformXML2Map' function
%    metStructure:  Second OUTPUT obtained when running checkCDerrors
%    metList:       List of metabolites with right names
%
% OUTPUT:
%    map:          Corrected map
%
% .. Author: - J.modamio 18/07/2017. Belval, Luxembourg, 18/07/2017.

    met = metStructure;
    for i = 1:length(met.extraMetsMap)
        index = find(ismember(map.specName, met.extraMetsMap{i}));
        map.specName(index, 1) = metList(i);
    end

end
