Description of errorComputation2
errorComputation2
PURPOSE
SYNOPSIS
function [out] = errorComputation2(x,Prob)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
scoreC13Fit
This function is called by:
C13ConfidenceInterval v0 - set of flux vectors to be used as initial guesses. They may be
errorComputation2_grad
SOURCE CODE
function [out] = errorComputation2(x,Prob)
expdata = Prob.user.expdata;
model = Prob.user.model;
out = 0;
if iscell(expdata)
    for i = 1:length(expdata)
        t = scoreC13Fit(x,expdata{i},model);
        out = out + t.error;
    end
else
    t = scoreC13Fit(x,expdata,model);
    out = t.error;
end
% if isfield(Prob.user, 'scaled')
%     out = out*Prob.user.scaled;
% end
if isfield(Prob.user, 'objective')
    error = out;
    out = Prob.user.objective'*x;
    if error > Prob.user.max_error
        out = out + Prob.user.multiplier*(Prob.user.max_error-error)^2;
    end
end
if isnan(out)
    save errorFile x Prob
end
return;