Description of idv2cdv
idv2cdv
PURPOSE
returns transformation to go from idv to cumomers.
SYNOPSIS
function [out] = idv2cdv(n)
DESCRIPTION
 returns transformation to go from idv to cumomers.
 cdv = idv2cdv(log2(length(idv)))*idv;
CROSS-REFERENCE INFORMATION
This function calls:
idv2cdv returns transformation to go from idv to cumomers.
This function is called by:
idv2cdv returns transformation to go from idv to cumomers.
compareBinsOfFluxes takes the overall sammin and sammax samples, bins them into
compareMultSamp Compare the multiple sets of samples
compareTwoSamp Compare the 2 sets of samples
getBinsOfFluxes take a samp.points fluxes and bin them by numfluxes (remainder not used)
getCompareBinsOfFluxes compares the bins of fluxes between samplo and samphi
SOURCE CODE
function [out] = idv2cdv(n)
% returns transformation to go from idv to cumomers.
% cdv = idv2cdv(log2(length(idv)))*idv;
if n <= 0
    out = [1];
    return;
end
T = idv2cdv(n-1);
out = [T,T;zeros(size(T)),T];