function [r_info]=correct_M(ref,listN,listR)

% Correct the inconsistent species name in the test model (identified by
% the 'cmpM' function) according to a reference list of species names.
%
%INPUTS
%
% ref           A parsed CD model structure generated by 'parseCD'function.
% listN         A list of species names that are present in the reference
%               model, but not in the test model; the list is the output of
%               the 'cmpM' function.
% listR         A new list of species names that will be used to substitute
%               the incorrect names (as listed in 'listN')
% 
%OUTPUTS
%
% r_info        The corrected CD model structure
%
%
%EXAMPLE
% 
% ref_corrected=correct_M(ref,cmp_recon2map_M.listOfNotFound(:,6),listForCorrection(:,2))
%
% Longfei Mao Oct/2014

col_name=2;


r_info=ref.r_info;
r_listN=listN
r_listR=listR


for n=1:length(r_listR)
    r_info.species(r_listN{n},col_name)=r_listR(n);
end


