function [ dummy ] = writeText2XML( text, fname_out )
%
%
% An auxiliary function to write the lines of text generated by other
% CD package functions to a XML file.
% 
%INPUTS
% 
% text          A matlab variable contains the lines of the variable to be
%               written to a XML file.
% fanme_out     The name of the output XML file name.
% 
% 
% Longfei Mao Oct/2014

if nargin<2 || isempty(fname_out)    
    
    [fname_out, fpath]=uiputfile('*.xml','CellDesigner SBML Source File');
    if(fname_out==0)
        return;
    end
    f_out=fopen([fpath,fname_out],'w');
else
    f_out=fopen(fname_out,'w');
end

for d=1:length(text);
    
    fprintf(f_out,'%s\n',char(text(d).str));
end

fclose(f_out);

end


