function [newMap] = addNotes(model, map)
% Function to add notes from a model to a metabolic map
%
% USAGE:
%
%   [newMap] = addNotes(model, map)
%
% INPUTS:
%   model:          COBRA model
%   map:            A parsed model structure generated by 
%                   'transformXML2MatStruct' function
%
% OUPUT:
%   newMap:         Modified map containing notes from the model
%
% .. Authors:
%       - A.Danielsdottir 20/07/2017 LCSB. Belval. Luxembourg.
%       - N.Sompairac - Institut Curie, Paris, 20/10/2017.

    newMap = map;

    a = 'Full name:';
    b = 'Abbreviation:';
    c = 'Formula:';
    d = 'Charge:';
    e = 'Descrition:';
    f = 'Annotations:';

    % Find only metabolites ( no subsystems added as a unknown metabolite) 
    listmets = strfind(newMap.specName, ']'); 
    index= ~cellfun(@isempty, listmets);
    listmets=newMap.specName(index,1);
    % Obtain abbreviation of each metabolite (split the indicator of
    % compartment) 
    G = regexp(listmets,'[','split');
    
    for i = 1:length(G)
        G2 = G{i,1};
        abbreviation(i,1) = G2(1);
    end 
 
    for i = 1:length(listmets)
        met = listmets(i);
        idx_model = find(ismember(model.mets,met));
        idx_new_map = find(ismember(newMap.specName,met));
        
        % Avoid possible errors. Have into account possible extra IDs
        % for same metabolite (this shouldn't be)...
        if length(idx_new_map) > 1
            for v = 1:length(idx_new_map)
                idx = idx_new_map(v);
                metAbbreviation = abbreviation{i};
                metName = char(model.metNames{idx_model});
                metFormula = char(model.metFormulas(idx_model));
                metCharge = num2str(model.metCharge(idx_model));
                summary = [a metName b metAbbreviation c metFormula d metCharge e f];
                newMap.specNotes{idx,1} = [newMap.specNotes{idx} newline summary];
            end
        else
            metAbbreviation = abbreviation{i};
            metName = char(model.metNames(idx_model));
            metFormula = char(model.metFormulas(idx_model));
            metCharge = num2str(model.metCharge(idx_model));
            summary = [a metName b metAbbreviation c metFormula d num2str(metCharge) e f];
            newMap.specNotes{idx_new_map,1} = [newMap.specNotes{idx_new_map} newline summary];
        end
    end
    
    % Add reactions notes
    g = 'Formula: ';
    h = 'Mechanical Confidence Score: ';
    k = 'Lower Bound: ';
    l = 'Upper Bound: ';
    m = 'Subsystem: ';
    n = 'Description: Type';

    listRxns = newMap.rxnName;
    Formula = printRxnFormula(model,listRxns);
    
    for j = 1:length(listRxns)
        rxn = listRxns(j);
        idx_model = find(ismember(model.rxns,rxn));
        formula = Formula{j};
        score = char(model.rxnConfidenceScores(idx_model));
        lower = num2str(model.lb(idx_model));
        upper = num2str(model.ub(idx_model));
        sub = char(model.subSystems(idx_model));
        type = char(newMap.rxnType{j});       
        summary = [g,formula,h,score,k,lower,l,upper,m,sub,n,type];
        disp(summary)
        newMap.rxnNotes{j,1} = [newMap.rxnNotes{j},newline,summary];
    end

end