function [map2] = changeRxnType(map,rxnsList,rxnsType)

    % Change reactions type for a specific list of reactions.
    % For example, pass from 'STATE_TRANSITION' to 'TRANSPORT'.
    %
    % USAGE:
    %
    %    [map2] = changeRxnType(map,listRxns,typeRxns) 
    %
    % INPUTS:
    %
    %    map:          A parsed model structure generated by 
    %                  'Transform_XML_to_Matlab_structure' function
    %
    %    rxnsList:     List of reactions names want to be changed
    %
    %    rxnsType:     string (new reaction type) 
    %
    % OUTPUT:
    %
    %    map2:          New parsed file with the changes in the reactions   
    %    
    % .. Author:
    % J.modamio 18/07/2017. Belval, Luxembourg.
    % N.Sompairac - Institut Curie, Paris, 11/10/2017. (Code cheking)

    % rename map to do not overwrite 
    map2 = map;

    % find the reaction ID in the map from the list of reactions (rxnsList)
    index = ismember(map2.rxnName,rxnsList);

    % substitute the reaction type 
    map2.rxnType(index,1) = {rxnsType};

end 
