function [map2] = changeNodesArea(map, metList, height, width)

% Change the area size of a list of metabolites (standardize the map)
%
% USAGE:
%
%    [map2] = changeNodesArea(map,metList,heigth,width)
%
% INPUTS:
%
%    map:          A parsed model structure generated by 
%                  'transformXML2MatStruct' function
%
%    metList:      list of metabolites which area wants to be changed  
%
% OPTIONAL INPUTS: 
%    
%    Height:       change height
%    Width:        change width 
%
% OUTPUT:
%
%    map2:          New parsed file with the changes in the reactions   
%     
% .. Authors:
% .. J.modamio 18/07/2017. Belval, Luxembourg, 18/07/2017.
% .. N.Sompairac - Institut Curie, Paris, 11/10/2017. (Code checking)

    if nargin<3
        height = 25.0; 
        if nargin<4
            width = 70.0;
        end
    end

    % Rename map 
    map2 = map;
    
    % Find mets in the map
    ID = map2.specID(ismember(map2.specName,metList));
    idx = find(ismember(map2.molID,ID));
    
    % Change Height
    map2.molHeight(idx,1) = {height};
    
    % Change Width 
    map2.molWidth(idx,1) = {width};

end 