function map = correctMetNameCD(map, metStructure, metList)

    % Correct the list of wrong metabolites name obtained from checkCDerrors
    % given a list of metabolites with the right names 
    %
    % INPUTS:
    %
    %    map:          A parsed model structure generated by 
    %                  'Transform_XML_to_Matlab_structure' function
    %
    %    metStructure: second OUTPUT obtained when running checkCDerrors 
    %
    %    metList:      list of metabolites with right names 
    %
    % OUTPUT:
    %
    %    map:          corrected map   
    %   
    % .. Author: J.modamio 18/07/2017. Belval, Luxembourg, 18/07/2017.

    met = metStructure; %renaming 

    for i = 1:length(met.extra_mets_map)
        
        index = find(ismember(map.specName,met.extra_mets_map{i}));
        map.specName(index,1) = metList(i);
        
    end
    
end 