function map = correctRxnNameCD(map, Rxn_stucture, RxnList)

% Correct the list of wrong reaction names obtained from checkCDerrors
% given alist of reactions with the right names 
%
% USAGE:
%
%   mmap = correctRxnNameCD(map, Rxn_stucture, RxnList)
%
% INPUTS:
%
%    map:          A parsed model structure generated by 
%                  'transformXML2MatStruct' function
%
%    Rxn_stucture: First OUTPUT obtained when running checkCDerrors 
%
%    RxnList:      list of reactions with right names 
%
% OUTPUT:
%
%    map:          corrected map   
%   
% .. Author: J.modamio 18/07/2017. Belval, Luxembourg, 18/07/2017.

    rxn = Rxn_stucture;
    for i = 1:length(rxn.extra_rxns_map) 
        index = find(ismember(map.rxnName,rxn.extra_rxns_map{i}));
        map.rxnName(index,1) = RxnList(i);
    end
    
end 