Description of columnVector
columnVector
PURPOSE
columnVector Converts a vector to a column vector
SYNOPSIS
function vec = columnVector(vec)
DESCRIPTION
columnVector Converts a vector to a column vector
 vec = columnVector(vec)
 Markus Herrgard
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
changeGeneAssociation changeGeneAssociation Change gene associations in a model
convertIrrevFluxDistribution convertInrrevFluxDistribution Convert irreversible flux distribution to
convertToIrreversible convertToIrreversible Convert model to irreversible format
convertToReversible convertToReversible convert a model structure from reversible format to
findCarbonRxns findHiCarbonRxns returns the list of reactions that act of compounds which
findHiCarbonRxns findHiCarbonRxns returns the list of reactions that act of compounds which
setConstraintsIrrevModel setConstraintsIrrevModel Set constraints for a subset of rxns while
findGenesFromRxns findGenesFromRxns make a gene list of the genes that correspond to the
fluxVariability fluxVariability Performs flux variablity analysis
generateDoc generateDoc uses m2html to create a set of html docs
convertSBMLToCobra convertSBMLToCobra Convert SBML format model (created using SBML Toolbox)
readBooleanRegModel readBooleanRegModel Read Boolean regulatory network model
readCbModel readCbModel Read in a constraint-based model
readSimPhenyCMPD readSimPhenyCMPD Read SimPheny compound file obtained from admin console
readSimPhenyGPR readSimPhenyGPR Read SimPheny gene-protein-reaction association file obtained from admin console
readSimPhenyGprText readSimPhenyGprText Parses SimPheny GPRA's in text format into a rxn x gene association
xls2model xls2model Writes a model from Excel spreadsheet.
optimizeCbModel optimizeCbModel Solve a flux balance analysis problem
pFBA Parsimoneous enzyme usage Flux Balance Analysis - method that optimizes
parseMetNames parseMetNames Figure out the base metabolite names and compartments for each metabolite
biomassPrecursorCheck biomassPrecursorCheck Checks if biomass precursors are able to be
reduceModel reduceModel Removes from the model all of the reactions that are never used (max and
removeCorrelRxns removeCorrelRxns Remove fully or almost fully correlated reactions
singleRxnDeletion singleRxnDeletion Performs single reaction deletion analysis using FBA,
solveCobraLP solveCobraLP Solve constraint-based LP problems
solveCobraMILP solveCobraMILP Solve constraint-based MILP problems
countUnique countUnique Count unique elements in a vector (cell array or numerical)
splitString splitString Splits a string Perl style
SOURCE CODE
function vec = columnVector(vec)
%columnVector Converts a vector to a column vector
%
% vec = columnVector(vec)
%
% Markus Herrgard
[n,m] = size(vec);
if (n < m)
    vec = vec';
end