Description of getCompartment
getCompartment
PURPOSE
Get the compartment for each metabolite, and the unique compartments
SYNOPSIS
function [compartments,uniqueCompartments]=getCompartment(mets,numChar)
DESCRIPTION
 Get the compartment for each metabolite, and the unique compartments
INPUT
 mets      m x 1 cell array of metabolite abbreviations with compartment
           concatentated on the right hand side
           i.e. metAbbr[*]
 OPTIONAL INPUT
 numChar   number of characters in compartment identifier (default = 1)
 OUTPUT
 compartments          m x 1 cell array of compartment identifiers
 uniqueCompartments    cell array of unique compartment identifiers
Ronan M.T. Fleming
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
setCommonZeroStandardGibbsEnergyOfFormation Set all Alberty's cofactor metabolites to have a common thermodynamic baseline.
thermodynamicAdjustmentToStoichiometry Thermodynamic adjustments to the stoichiometric matrix for co2, h2o, and bound cofactors.
convertToCobraV2 Generate a model structure with metabolite and reaction subfields instead of vectors.
deltaG0concFluxConstraintBounds set reaction directionality bounds from thermodynamic data
pHbalanceProtons Mass balance protons for each reaction by adjusting the hydrogen ion stoichiometric coefficient.
setupThermoModel Thermodynamically constrains a COBRA model.
testInterCompartmentRxn Calculates the transformed Gibbs energy for a reaction and
transportReactionBool Return a boolean vector indicating which reactions transport between compartments.
SOURCE CODE
function [compartments,uniqueCompartments]=getCompartment(mets,numChar)
% Get the compartment for each metabolite, and the unique compartments
%
%INPUT
% mets      m x 1 cell array of metabolite abbreviations with compartment
%           concatentated on the right hand side
%           i.e. metAbbr[*]
%
% OPTIONAL INPUT
% numChar   number of characters in compartment identifier (default = 1)
%
% OUTPUT
% compartments          m x 1 cell array of compartment identifiers
% uniqueCompartments    cell array of unique compartment identifiers
%
%Ronan M.T. Fleming
if ~exist('numChar','var')
    numChar=1;
end
nMet=length(mets);
compartments=cell(nMet,1);
for m=1:nMet
    compartments{m} = mets{m}(end-numChar:end-1);
end
uniqueCompartments=unique(compartments);