% isomorphismLabelOnlyCheck.m
%
% Non-CI reproducibility check and benchmark for feature
% 20260930-102230-isomorphism-label-only-copies (tasks.md T006; spec FR-002, FR-004, FR-008,
% SC-001 to SC-004; research R4, R5).
%
% The pre-change helper is FEATURE/baseline/classifySubgraphIsomorphism.m (a verbatim copy of
% commit f4a62639e). It is put in front of the source on the path only for baseline runs, and
% the active file is asserted before every run.
%   1. classifies the 39,916 component subgraphs of the 1,960-reaction model with
%      'NodeVariables','mets' using the baseline and the source helper; compares all three
%      outputs and the isisomorphic call count; reports both times (SC-002);
%   2. runs identifyConservedReactingMoieties end to end (conserved moieties only) with the
%      baseline and the source helper, compares the source run with the golden outputs and the
%      two total isisomorphic call counts (SC-001, SC-004);
%   3. unless CBT_ILO_NO_TIMING=1: 5 alternating timed runs (CBT_ILO_TIMING_RUNS overrides) of
%      the same end-to-end call, baseline then source, and the SC-003 gate (median ratio <= 0.60);
% and appends the results to isomorphismLabelOnlyResults.md.
%
% USAGE (headless, after initCobraToolbox):
%   setenv('CBT_ILO_NO_TIMING', '1');   % optional: equality and call counts only
%   setenv('CBT_ILO_TIMING_ONLY', '1'); % optional: skip sections 1-2 (re-measure timing only)
%   run('/home/jackmcgoldrick/cobratoolbox/specs/20260930-102230-isomorphism-label-only-copies/isomorphismLabelOnlyCheck.m')

featureDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(fileparts(featureDir));
baselineDir = fullfile(featureDir, 'baseline');
srcPath = fullfile(repoRoot, 'src', 'analysis', 'topology', 'reactingMoieties', ...
    'classifySubgraphIsomorphism.m');
baselinePath = fullfile(baselineDir, 'classifySubgraphIsomorphism.m');
homeDir = char(java.lang.System.getProperty('user.home'));
outputsDir = fullfile(homeDir, 'repos', 'reconXmoieties', 'experiments', 'moietySizing', ...
    'results', 'outputs');
resultsPath = fullfile(featureDir, 'isomorphismLabelOnlyResults.md');

[~, gitCommit] = system(sprintf('git -C "%s" rev-parse --short HEAD', repoRoot));
[~, gitDirty] = system(sprintf('git -C "%s" status --porcelain -- src', repoRoot));
srcState = strtrim(gitCommit);
if ~isempty(strtrim(gitDirty))
    srcState = [srcState '+modified'];
end
runTime = char(datetime('now', 'TimeZone', 'UTC', 'Format', 'yyyy-MM-dd HH:mm'));
if ~isfile(resultsPath)
    fid = fopen(resultsPath, 'w');
    fprintf(fid, ['# Results: classify isomorphism on label-only copies\n\n' ...
        'Feature `20260930-102230-isomorphism-label-only-copies`. Base commit `f4a62639e`. ' ...
        'Generated by `isomorphismLabelOnlyCheck.m`; append-only.\n']);
    fclose(fid);
end

timingOnly = strcmp(getenv('CBT_ILO_TIMING_ONLY'), '1');
isIdentical = true;
inputs = load(fullfile(outputsDir, 'conservedMoietyHotspots', 'n1960-identifyInputs.mat'), ...
    'model', 'BG', 'dATM');
options = struct('sanityChecks', 0, 'conservedMoietiesOnly', true);
if ~timingOnly
%% 1. component classification on the real 1,960-reaction subgraphs
S = load(fullfile(outputsDir, 'extractBondSubgraphsPeeling', 'n1960-inputs.mat'), 'ATG');
componentSubgraphs = extractPartitionSubgraphs(S.ATG, conncomp(S.ATG)');
clear S
useHelper(baselineDir, baselinePath, true);
[baselineCounts, baselineOut, baselineSeconds] = classifyOnce(componentSubgraphs);
useHelper(baselineDir, srcPath, false);
[sourceCounts, sourceOut, sourceSeconds] = classifyOnce(componentSubgraphs);
sameClassification = isequal(baselineOut, sourceOut);
sameComponentCount = baselineCounts == sourceCounts;
clear componentSubgraphs

%% 2. end-to-end equality and total call count
useHelper(baselineDir, baselinePath, true);
classifySubgraphIsomorphism('resetCallCount');
identifyConservedReactingMoieties(inputs.model, inputs.BG, inputs.dATM, options);
baselineTotalCount = classifySubgraphIsomorphism('getCallCount');
useHelper(baselineDir, srcPath, false);
classifySubgraphIsomorphism('resetCallCount');
[arm, moietyFormulae, reacting] = identifyConservedReactingMoieties(inputs.model, inputs.BG, ...
    inputs.dATM, options);
sourceTotalCount = classifySubgraphIsomorphism('getCallCount');
golden = load(fullfile(outputsDir, 'extractBondSubgraphsPeeling', 'n1960-endToEnd-golden.mat'), ...
    'arm', 'moietyFormulae', 'reacting');
sameArm = isequaln(arm, golden.arm);
sameFormulae = isequaln(moietyFormulae, golden.moietyFormulae);
sameReacting = isequaln(reacting, golden.reacting);
clear arm moietyFormulae reacting golden
sameTotalCount = baselineTotalCount == sourceTotalCount;
isIdentical = sameClassification && sameComponentCount && sameArm && sameFormulae && ...
    sameReacting && sameTotalCount;

fid = fopen(resultsPath, 'a');
fprintf(fid, ['\n### Equality and call counts, %s UTC, source %s\n\n' ...
    '- Component classification (39,916 subgraphs, NodeVariables mets): identical %s; ' ...
    'isisomorphic calls baseline %d, source %d; time baseline %.1f s, source %.1f s, ratio %.3f (SC-002)\n' ...
    '- End to end (n1960, conserved-only): arm %s, moietyFormulae %s, reacting %s; ' ...
    'total isisomorphic calls baseline %d, source %d (SC-004 %s)\n'], runTime, srcState, ...
    yesNo(sameClassification), baselineCounts, sourceCounts, baselineSeconds, sourceSeconds, ...
    sourceSeconds / baselineSeconds, yesNo(sameArm), yesNo(sameFormulae), yesNo(sameReacting), ...
    baselineTotalCount, sourceTotalCount, ternary(sameTotalCount, 'equal', 'DIFFERENT'));
fclose(fid);
fprintf(['classification identical %d, calls %d/%d, %.1f s -> %.1f s; end to end arm %d formulae %d ' ...
    'reacting %d, total calls %d/%d\n'], sameClassification, baselineCounts, sourceCounts, ...
    baselineSeconds, sourceSeconds, sameArm, sameFormulae, sameReacting, baselineTotalCount, ...
    sourceTotalCount);
end

%% 3. timing gate (SC-003)
gateFailed = false;
if ~strcmp(getenv('CBT_ILO_NO_TIMING'), '1')
    nRuns = 5;
    if ~isempty(getenv('CBT_ILO_TIMING_RUNS'))
        nRuns = str2double(getenv('CBT_ILO_TIMING_RUNS'));
    end
    [~, loadBefore] = system('uptime');
    baselineRuns = zeros(nRuns, 1);
    sourceRuns = zeros(nRuns, 1);
    for run = 1:nRuns
        useHelper(baselineDir, baselinePath, true);
        tStart = tic;
        identifyConservedReactingMoieties(inputs.model, inputs.BG, inputs.dATM, options);
        baselineRuns(run) = toc(tStart);
        useHelper(baselineDir, srcPath, false);
        tStart = tic;
        identifyConservedReactingMoieties(inputs.model, inputs.BG, inputs.dATM, options);
        sourceRuns(run) = toc(tStart);
        fprintf('timing run %d: baseline %.1f s, source %.1f s\n', run, baselineRuns(run), sourceRuns(run));
    end
    [~, loadAfter] = system('uptime');
    ratio = median(sourceRuns) / median(baselineRuns);
    gateFailed = ratio > 0.60;
    isInconsistent = any(baselineRuns > 1.5 * median(baselineRuns)) || ...
        any(sourceRuns > 1.5 * median(sourceRuns));
    fid = fopen(resultsPath, 'a');
    fprintf(fid, ['\n### Timing, %s UTC, source %s, %d alternating runs each' ...
        ternary(timingOnly, ' (timing only; equality verified in the earlier entries)', '') '\n\n' ...
        '- Load before: %s\n- Load after: %s\n' ...
        '- Baseline runs: %s s; source runs: %s s\n' ...
        '- **SC-003 (gate)**: median source/baseline = %.1f / %.1f = %.3f (limit 0.60): %s%s\n'], ...
        runTime, srcState, nRuns, strtrim(loadBefore), strtrim(loadAfter), ...
        mat2str(baselineRuns', 4), mat2str(sourceRuns', 4), median(sourceRuns), ...
        median(baselineRuns), ratio, ternary(gateFailed, 'FAIL', 'PASS'), ...
        ternary(isInconsistent, ' — runs inconsistent (a run above 1.5× its siblings'' median): repeat per SC-003', ''));
    fclose(fid);
    fprintf('SC-003 ratio %.3f (%s)%s\n', ratio, ternary(gateFailed, 'FAIL', 'PASS'), ...
        ternary(isInconsistent, ' INCONSISTENT', ''));
end
useHelper(baselineDir, srcPath, false);

if ~isIdentical
    error('isomorphismLabelOnlyCheck:mismatch', ...
        'Outputs or call counts differ from the pre-change helper; see %s.', resultsPath);
end
if gateFailed
    error('isomorphismLabelOnlyCheck:gate', ...
        'SC-003 failed: the median ratio is above 0.60; see %s.', resultsPath);
end

%% Local functions
function useHelper(baselineDir, expectedPath, useBaseline)
% Put the baseline helper in front of the source (or remove it) and assert which is active
if useBaseline
    addpath(baselineDir, '-begin');
elseif contains(path, baselineDir)
    rmpath(baselineDir);
end
activePath = which('classifySubgraphIsomorphism');
if ~strcmp(activePath, expectedPath)
    error('isomorphismLabelOnlyCheck:wrongHelper', ...
        'Active classifySubgraphIsomorphism is %s, expected %s.', activePath, expectedPath);
end
end

function [callCount, outputs, seconds] = classifyOnce(subgraphs)
classifySubgraphIsomorphism('resetCallCount');
tStart = tic;
[classes, firsts, subsequent] = classifySubgraphIsomorphism(subgraphs, 'NodeVariables', 'mets');
seconds = toc(tStart);
callCount = classifySubgraphIsomorphism('getCallCount');
outputs = {classes, firsts, subsequent};
end

function s = yesNo(tf)
s = ternary(tf, 'yes', 'NO');
end

function out = ternary(condition, a, b)
if condition
    out = a;
else
    out = b;
end
end
