% The COBRAToolbox: testPanModels.m
%
% Purpose:
%     - tests that pan-species models generated by the createPanModels
%     function can produce biomass and produce reasonable amounts of ATP
%
% Author:
%     - Almut Heinken - September 2021
%
% Note:
%     - The solver libraries must be included separately

% initialize the test
fileDir = fileparts(which('testCreatePanModels'));
cd(fileDir);

% load the AGORA models
websave('AGORA-master.zip','https://github.com/VirtualMetabolicHuman/AGORA/archive/master.zip')
try
    unzip('AGORA-master')
end
modPath = [pwd filesep 'AGORA-master' filesep 'CurrentVersion' filesep 'AGORA_1_03' filesep' 'AGORA_1_03_mat'];

% create the pan-models
panPath=[pwd filesep 'panSpeciesModels'];

numWorkers=4;

createPanModels(modPath,panPath,'Species',numWorkers);

% test the pan-models
[notGrowing,Biomass_fluxes] = plotBiomassTestResults(panPath, 'pan-models','numWorkers',numWorkers);
assert(isempty(notGrowing))

[tooHighATP,ATP_fluxes] = plotATPTestResults(panPath, 'pan-models','numWorkers',numWorkers);
assert(isempty(tooHighATP))
