% The COBRAToolbox: testPanModels.m
%
% Purpose:
%     - tests that pan-species models generated by the createPanModels
%     function can produce biomass and produce reasonable amounts of ATP
%
% Author:
%     - Almut Heinken - September 2021
%
% Note:
%     - The solver libraries must be included separately

% initialize the test
fileDir = fileparts(which('testCreatePanModels'));
cd(fileDir);

% load the AGORA models
websave('AGORA-master.zip','https://github.com/VirtualMetabolicHuman/AGORA/archive/master.zip')
try
    unzip('AGORA-master')
end
modPath = [pwd filesep 'AGORA-master' filesep 'CurrentVersion' filesep 'AGORA_1_03' filesep' 'AGORA_1_03_mat'];

numWorkers=4;

% create the pan-models on species level
panPath=[pwd filesep 'panSpeciesModels'];

createPanModels(modPath,panPath,'Species','AGORA',numWorkers);

% test that pan-models can grow
[notGrowing,Biomass_fluxes] = plotBiomassTestResults(panPath, 'pan-models','numWorkers',numWorkers);
% assert(isempty(notGrowing))
if ~isempty(notGrowing)
    disp('Some models are not growing. Do you want to stop the execution?');
    userInput = input('Type "y" to stop, or "n" to continue: ', 's');
    
    if strcmpi(userInput, 'y')
        error('Execution stopped because some models are not growing in panSpeciesModels');
    else
        disp('Continuing the execution despite some models not growing in panSpeciesModels');
    end
end

% test that ATP production is not too high
[tooHighATP,ATP_fluxes] = plotATPTestResults(panPath, 'pan-models','numWorkers',numWorkers);
% assert(max(cell2mat(ATP_fluxes(2:end,2))) < 200)
% assert(max(cell2mat(ATP_fluxes(2:end,3))) < 150)
% Check the Aerobic ATP production
if max(cell2mat(ATP_fluxes(2:end,2))) >= 200
    disp(['The maximum ATP flux in ',cell2mat(ATP_fluxes(1,2)),' exceeds 200.']);
    userInput = input('Type "y" to stop, or any other key to continue: ', 's');
    
    if strcmpi(userInput, 'y')
        error(['Execution stopped because the maximum ATP flux in ', cell2mat(ATP_fluxes(1,2)),'panSpeciesModels exceeds 200.']);
    else
        disp(['Continuing despite ATP flux exceeding 200 in ', cell2mat(ATP_fluxes(1,2)), 'panSpeciesModels']);
    end
end
% Check the Anaerobic ATP production
if max(cell2mat(ATP_fluxes(2:end,3))) >= 150
    disp(['The maximum ATP flux in ',cell2mat(ATP_fluxes(1,3)),' panSpeciesModels exceeds 150.']);
    userInput = input('Type "y" to stop, or "n" to continue: ', 's');
    
    if strcmpi(userInput, 'y')
        error(['Execution stopped because the maximum ATP flux in ', cell2mat(ATP_fluxes(1,3)),' panSpeciesModels exceeds 150.']);
    else
        disp(['Continuing despite ATP flux exceeding 150 in ', cell2mat(ATP_fluxes(1,3)), 'panSpeciesModels']);
    end
end

% create the pan-models on genus level
panPath=[pwd filesep 'panGenusModels'];

createPanModels(modPath,panPath,'Genus','AGORA',numWorkers);

% test that pan-models can grow
[notGrowing,Biomass_fluxes] = plotBiomassTestResults(panPath, 'pan-models','numWorkers',numWorkers);
%assert(isempty(notGrowing))
if ~isempty(notGrowing)
    disp('Some models are not growing. Do you want to stop the execution?');
    userInput = input('Type "y" to stop, or "n" to continue: ', 's');
    
    if strcmpi(userInput, 'y')
        error('Execution stopped because some models are not growing in panGenusModels');
    else
        disp('Continuing the execution despite some models not growing in panGenusModels');
    end
end

% test that ATP production is not too high
[tooHighATP,ATP_fluxes] = plotATPTestResults(panPath, 'pan-models','numWorkers',numWorkers);
% assert(max(cell2mat(ATP_fluxes(2:end,2))) < 250)
% assert(max(cell2mat(ATP_fluxes(2:end,3))) < 200)

% Check the Aerobic ATP production
if max(cell2mat(ATP_fluxes(2:end,2))) >= 250
    disp(['The maximum ATP flux in ',cell2mat(ATP_fluxes(1,2)),' panSpeciesModels exceeds 200.']);
    userInput = input('Type "y" to stop, or "n" to continue: ', 's');
    
    if strcmpi(userInput, 'y')
        error(['Execution stopped because the maximum ATP flux in ', cell2mat(ATP_fluxes(1,2)),' panSpeciesModels exceeds 200.']);
    else
        disp(['Continuing despite ATP flux exceeding 200 in ', cell2mat(ATP_fluxes(1,2)), 'panSpeciesModels']);
    end
end
% Check the Anaerobic ATP production
if max(cell2mat(ATP_fluxes(2:end,3))) >= 200
    disp(['The maximum ATP flux in ',cell2mat(ATP_fluxes(1,3)),' exceeds 150.']);
    userInput = input('Type "y" to stop, or "n" to continue: ', 's');
    
    if strcmpi(userInput, 'y')
        error(['Execution stopped because the maximum ATP flux in ', cell2mat(ATP_fluxes(1,3)),' model exceeds 150.']);
    else
        disp(['Continuing despite ATP flux exceeding 150 in ', cell2mat(ATP_fluxes(1,3))]);
    end
end